/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Default Save": "默认存档",
    "Delete": "删除",
    "No": "否",
    "Saves": "存档",
    "Options": "选项",
    "Yes": "是",
    "Are you sure?": "你确定吗？",
    "Edit Name": "编辑名称",
    "Info": "信息",
    "Currently:": "当前:",
    "Appearance": "外观",
    "How the game looks.": "游戏看起来如何。",
    "Theme": "主题",
    "Show milestones": "显示里程碑",
    "Show TPS meter at the bottom-left corner of the page.": "在页面左下角显示 TPS。",
    "Show TPS": "显示 TPS",
    "None": "无",
    "Align modifier units": "对齐概览单位",
    "Align numbers to the beginning of the unit in modifier view.": "在概览视图中将数字与单元的开头对齐。",
    "Select which milestones to display based on criterias.": "根据标准选择要显示的里程碑。",
    "All": "全部",
    "Classic": "经典",
    "Configurable": "可配置",
    "Duplicate": "复制",
    "Mute": "静音",
    "Unmute": "播放",
    "New Game": "新游戏",
    "Normal": "正常",
    "Name": "名称",
    "OK": "确定",
    "Network": "网络",
    "Network connec": "网络连接",
    "Max": "最大",
    "Last Played": "最近游戏",
    "Keyboard": "键盘",
    "Automation bots": "自动化机器人",
    "Click": "点击",
    "Click mode": "点击模式",
    "Booting...": "正在启动...",
    "Confirm": "确认",
    "Confirm selection": "确认选项",
    "Console": "控制台",
    "Console Idle": "控制台放置",
    "Continue": "继续",
    "Welcome": "欢迎",
    "Toggle Auto block": "切换自动阻止",
    "Updates Notes": "更新日志",
    "Toggle Auto Software Install": "切换自动软件安装",
    "Updates": "更新",
    "Hrdwares": "硬件",
    "Idle repoert": "放置报表",
    "Idle report": "放置报告",
    "Install All": "全部安装",
    "Listener": "监听器",
    "Logout": "登出",
    "Lord Beranda": "勋爵之家",
    "Format": "格式化",
    "Fixes:": "修复:",
    "Easy": "简单",
    "Details": "详情",
    "Data": "数据",
    "Creation Date": "创建日期",
    "Computing": "计算",
    "Export save file": "导出存档文件",
    "Exported save file": "已导出存档",
    "Exploring": "探索",
    "Firewall": "防火墙",
    "Pause": "暂停",
    "Hard": "困难",
    "Green": "绿色",
    "Return": "返回",
    "Resume": "继续",
    "RESET": "重置",
    "Reset": "重置",
    "Reset Tutorials": "重置教程",
    "Save file": "存档文件",
    "Save File": "存档文件",
    "Dowloands": "下载",
    "Downloading, Please wait...": "正在下载，请稍候...",
    "Store": "商店",
    "Filtering": "筛选",
    "General": "常规",
    "GET": "获取",
    "Generator": "发电机",
    "HACKED": "黑客入侵",
    "Hardwares": "硬件",
    "Heat": "热量",
    "Hibernate": "休眠",
    "HQ store": "HQ 商店",
    "Importing...": "导入...",
    "Software": "软件",
    "Softwares": "软件",
    "Solar power": "太阳能",
    "Sorting": "排序",
    "System": "系统",
    "System Color": "系统颜色",
    "System Manager": "系统管理员",
    "Tasks": "任务",
    "Task progress menu is now resizable": "任务进度菜单现在可调整大小",
    "Tasks now can be pasued/Resumed": "现在可以暂停/恢复任务",
    "The Authors of the icons are:": "图标的作者是：",
    "Turn OFF": "关掉",
    "TURN OFF": "关掉",
    "TURN ON": "打开",
    "Turn ON": "打开",
    "Turn OFF/ON idle report": "关闭/打开 放置报告",
    "Warehouse": "仓库",
    "Mouse": "鼠标",
    "Network, Please wait...": "网络，请稍等...",
    "OR Gate": "或门",
    "NOT Gate": "非门",
    "NAND Gate": "与非门",
    "NOR Gate": "或非门",
    "XOR Gate": "异或门",
    "Note: If Game still freezing or CPS not working, please send a feedback": "注意：如果游戏仍然冻结或 CPS 无法工作，请发送反馈",
    "Online Store": "在线商店",
    "Online store now will not show you upgrades for Hardwares that are not unlocked yet": "在线商店现在不会向您显示尚未解锁的硬件的升级",
    "Performance": "性能",
    "Retrigger all Tutorials": "重新触发所有教程",
    "Router": "路由器",
    "Satellite": "卫星",
    "'Cancel' Button in Format menu is now always visible": "“格式”菜单中的“取消”按钮现在始终可见",
    "%/Task": "%/任务",
    "> Changed to 'Pressing' Task on Easy mode": "> 更改为简易模式下的“按下”任务",
    "> Registration complate, Welcome Agent.": "> 登记已完成，欢迎新代理。",
    "> Save complete.": "> 保存完成。",
    "> saving...": "> 正在保存...",
    "Pressing": "按下",
    "Radio tower": "无线电塔",
    "Radar dish": "雷达天线",
    "Recycling": "回收",
    "Withdraw": "提取",
    "Systems": "系统",
    "Skoll": "斯科尔",
    "Sequence": "顺序",
    "Sequencer": "顺序器",
    "Select a File": "选择一个文件",
    "Scrapping": "废料",
    "Red": "红色",
    "RAM": "内存",
    "sbed": "错误检测",
    "Probably Fixed a bug where saving sometimes fail, Note: Refreshing the page might cause lose of all progress from last auto save, this is caused by browsers design, nothing i can do here, so please make sure to manually save before refreshing the page.": "可能修复了有时保存失败的错误，注意：刷新页面可能会导致上次自动保存的所有进度丢失，这是由浏览器设计引起的，我在这里无能为力，所以请确保在刷新页面之前手动保存。",
    "Lorc": "洛克希德公司无线电指令",
    ", under the terms of the Creative": "，根据创意条款",
    "A random sabotage effect will be applied, eicher Reducing CPS, DPS, CPC, MPM, Energy, or Network": "将应用随机破坏效果，即减少 CPS、DPS、CPC、MPM、能量或网络",
    "Achievement": "成就",
    "Add": "添加",
    "Adder": "加法器",
    "Adjusted all 'Advanced Decoding algorithms' softwares prices": "调整了所有“高级解码算法”软件的价格",
    "Adjusted All three tasks": "调整了全部三项任务",
    "Adjusted G.A.I.A Hack attempts intervelas, HACKS are less frequent in general": "调整后的 G.A.I.A 黑客尝试间隔，总体而言黑客攻击频率较低",
    "Adjusted in Tasks menu 'Overflow', 'Infinite keys' information text, to be more detailed.": "调整了任务菜单“溢出”、“无限键”信息文本，更加详细。",
    "All menus now should remember their status, position, size, opened or not, expanded or not": "现在所有菜单都应该记住它们的状态、位置、大小、是否打开、是否展开",
    "All menus will auto reset if 'Auto reset' is ON": "如果“自动重置”打开，所有菜单将自动重置",
    "All new precedures from Bot manager will also be calculated in Idle if they are active but not in Hibernate": "如果 Bot 管理器中的所有新程序处于活动状态，但不在 Hibernate 中，则它们也将在 Idle 中计算",
    "All Original icons assets are from": "所有原始图标资源均来自",
    "All three Tasks now have the same software effects, it is up to your preference to choose to invest and upgrade:": "现在三个任务的软件效果是一样的，可以根据自己的喜好选择投资升级：",
    "Analysis": "分析",
    "AND Gate": "与门",
    "Are you sure to PERMENENTLY reset current save file?": "您确定要永久重置当前保存文件吗？",
    "Assemble": "组装",
    "Assign": "分配",
    "Auto": "自动",
    "Balancing:": "平衡：",
    "Battle bots": "战斗机器人",
    "Blue": "蓝色",
    "Bot Manager": "机器人管理",
    "Cancel": "取消",
    "Casting": "铸件",
    "Chair": "椅子",
    "Change Listener bot effect to directly increase DPS": "改变Listener bot效果直接增加DPS",
    "Changes": "变化",
    "Changes:": "变化：",
    "Click on Effect viewer to toggle between pinning effect list or not, this helps when you want to scroll the list": "单击效果查看器可在是否固定效果列表之间切换，这在您想要滚动列表时很有帮助",
    "Clicker": "点击器",
    "Commons 3.0 BY license": "Commons 3.0 BY 许可证",
    "Completely new UI": "全新的用户界面",
    "Contact": "接触",
    "CPS and DPS AD Multipliers can now be increased up to x8 and increase duration to 20mins": "CPS 和 DPS AD 乘数现在可增加至 x8，并将持续时间增加至 20 分钟",
    "Credit": "积分",
    "Credits": "制作人员",
    "Currencies": "货币",
    "Decoder_agent": "解码器代理",
    "Decreased all Advanced Decoding algorithms software prices and condition to unlock": "降低了所有高级解码算法软件的价格和解锁条件",
    "defence bots": "防御机器人",
    "Delapouite": "德拉普伊特",
    "Desk": "办公桌",
    "Details page in System manager is now divided into sections for easier reading": "系统管理器中的详细信息页面现在分为多个部分，以便于阅读",
    "Energy": "能源",
    "Enter": "进入",
    "Extended basic tutorial to include an explanation about CPU, GPU, RAM, and Heat mechanics": "扩展基础教程，包括有关 CPU、GPU、RAM 和热机制的说明",
    "Extended main Tutorial pop-up messages to include an explanation about the Effect viewer": "扩展了主要教程弹出消息，包括有关效果查看器的说明",
    "FAN": "风扇",
    "G.A.I.A ADS Network_spy": "G.A.I.A ADS Network_spy",
    "G.A.I.A will sabotage the System for X minutes and X effect power, depending on Hack difficulty and G.A.I.A difficulty": "G.A.I.A 将破坏系统 X 分钟和 X 效果强度，具体取决于 Hack 难度和 G.A.I.A 难度",
    "game-icons.net": "游戏图标.net",
    "General performance improvements": "一般性能改进",
    "General Performance improvements": "一般性能改进",
    "General Software and hardware prices balancing": "一般软件和硬件价格平衡",
    "General visual improvements, and typo fixes": "一般视觉改进和拼写错误修复",
    "General Visual improvements, and typo fixes": "一般视觉改进和拼写错误修复",
    "General Visual improvments": "一般视觉改善",
    "General visual improvments, and typo fixes": "一般视觉改进和拼写错误修复",
    "General Visual polishing": "一般视觉抛光",
    "Green, Red, and Blue System's themes have been adjusted to fit the new UI": "绿色、红色和蓝色系统的主题已调整以适应新的用户界面",
    "Hardware resources consumption info now will change depending on current selected buy mode": "硬件资源消耗信息现在将根据当前选择的购买模式而变化",
    "Hardware's generating rate text info now includes the CPS ad multiplier.": "硬件的生成率文本信息现在包括 CPS 广告乘数。",
    "Hitting Walls or Seekers will end the HACK instantly resulting in being Hacked": "撞墙或搜索者将立即结束 HACK，导致被黑客攻击",
    "Idle generating is now affected by AD x2 CPS, DPS, for the buff duration": "空闲生成现在在 buff 持续时间内受到 AD x2 CPS、DPS 的影响",
    "improved main icons visuals, it is now almost similar to windows icons behavior": "改进了主图标的视觉效果，现在几乎与 Windows 图标行为相似",
    "Increased \"Tasks\" Tier 5 reward": "增加“任务”5级奖励",
    "Increased all Auto clicker effect node in format tree from +2% -> +3%": "增加格式树中所有自动点击器效果节点从 +2% -> +3%",
    "Increased all conditions of generated Credit from Addition Tasks": "增加了从加法任务中生成积分的所有条件",
    "Increased all conditions of total Hardwares and softwares achievements": "增加了总硬件和软件成就的所有条件",
    "Increased all Credits generated from tasks achievements conditions": "增加了任务成就条件产生的所有积分",
    "Increased all DPS achievements conditions": "增加了所有 DPS 成就条件",
    "Increased All Format nodes prices": "提高了所有格式节点的价格",
    "Increased almost all Online items effect by at least x3 depending on the item": "将几乎所有在线物品的效果增加至少 x3，具体取决于物品",
    "Increased Basic: CPS, DPS, CLICK": "增加基础：CPS、DPS、CLICK",
    "Increased Computing, Frequency, and all Gates softwares effects, now they give more CPS bonuses, and their descriptions is more clear": "增加了计算、频率和所有盖茨软件的效果，现在它们提供更多的CPS奖励，并且它们的描述更清晰",
    "Increased Credit and Data gain when successfully blocking a HACK, blocking Impossible difficulty is now significantly more rewarding": "成功阻止黑客攻击时，积分和数据增益增加，阻止不可能的难度现在明显更有价值",
    "Increased Credit gain when blocking HACK!": "阻止黑客攻击时增加积分增益！",
    "Increased Credit loss when HACKED!": "被黑客攻击时积分损失增加！",
    "Increased Crown Coin effect:": "增加皇冠币效果：",
    "Increased Data analysis and filtering program effect, now they give more DPS bonuses, and their description is more clear": "增加了数据分析和过滤程序效果，现在它们给予更多的DPS加成，并且它们的描述更清晰",
    "Increased Data gain when blocking HACK!": "阻止 HACK 时增加数据增益！",
    "Increased Data loss when HACKED!": "黑客攻击时数据丢失增加！",
    "increased Date requirement in Format tree for Firewall, Resourecs, Advanced decoding algorithem, Multithriding, and Store nodes tree": "增加了防火墙、资源、高级解码算法、多重处理和存储节点树的格式树中的日期要求",
    "Increased Firewall effect from increasing 2.5% per level to 5% per level": "防火墙效果从每级 2.5% 增加到每级 5%",
    "Increased Network listener effect node in format tree from +0.1% -> +0.2%": "格式树中的网络侦听器效果节点从 +0.1% -> +0.2% 增加",
    "Increased Online item sizes": "增加在线物品尺寸",
    "Increased Pressing task software unlocking conditions": "增加压制任务软件解锁条件",
    "Increased Pressing Tsk complation points from 20 to 25": "Pressing Tsk 编译点从 20 增加到 25",
    "Increased Rare: DPS": "增加稀有：DPS",
    "Increased Uncommon: DPS, CLICK": "增加罕见：DPS、点击",
    "Install all currently affordable Softwares": "安装所有当前负担得起的软件",
    "Installed Sequence softwares will be now showing in Software Page in System manager": "已安装的顺序软件现在将显示在系统管理器的软件页面中",
    "MangOperations": "MangOperations",
    "Material production": "材料生产",
    "Materials": "材料",
    "Mining": "采矿",
    "Miscellaneous": "杂项",
    "Monitor": "监视器",
    "New objective: reach the goal in the Lower right corner before times up": "新目标：在时间结束前到达右下角的目标",
    "New System lock visuals when Threat reaches 100%+": "当威胁达到 100% 以上时，新的系统锁定视觉效果",
    "New Tasks system:": "新任务系统：",
    "No effect currently activated": "当前未激活任何效果",
    "Now all Tasks can be played on Three difficulties, Easy, Normal, and Hard": "现在所有任务都可以在三种难度下进行：简单、正常和困难",
    "Now G.A.I.A will get bit by bit stronger with each Format, Hacks will be more frequent, difficult Hacks will appear more, and greater sabotaging when successfully hacked": "现在G.A.I.A的每种格式都会变得越来越强大，黑客攻击将会更加频繁，困难的黑客攻击将会出现更多，成功黑客攻击后破坏性也会更大",
    "NXOR Gate": "异或门",
    "Onion_protiection": "洋葱保护",
    "Open Updates patch notes": "打开更新补丁说明",
    "Permanently delete current save file": "永久删除当前保存文件",
    "Permanently reset currenct save file": "永久重置当前保存文件",
    "Presser": "压机",
    "Pressing, Addition, and Sequence Credit multipliers are changed to increase base Credit gain instead of increasing generally": "按下、加法和顺序积分乘数已更改，以增加基本积分增益，而不是普遍增加",
    "Pressing, Addition, and Sequence rewards multiplers are changed to scale with current CPS and DPS for each keyboard instead of increasing by fixed number, this way tasks rewards will always be meaningful and engaging!": "按下、加法和顺序奖励倍数会根据每个键盘的当前 CPS 和 DPS 进行调整，而不是按固定数字增加，这样任务奖励将始终有意义且有吸引力！",
    "Problebly fixed a bug where icons images sometimes does not load": "可能修复了图标图像有时无法加载的错误",
    "Procedure": "程序",
    "Processes": "流程",
    "Production": "生产",
    "Researched Format nods will now glow in gold": "研究的格式点头现在将发出金色光芒",
    "Second attempt to fix saving issues. Please provide feedback if bugs persist": "第二次尝试解决保存问题。 如果错误仍然存在，请提供反馈",
    "See Balancing section for more information": "有关详细信息，请参阅平衡部分",
    "Select a File": "选择一个文件",
    "Selected File: File09012024134339": "选定的文件：File09012024134339",
    "Slightly increased Credit gain when Blocking a HACK": "阻止黑客攻击时的积分增益略有增加",
    "Slightly increased Credit loss when Hacked": "被黑客攻击时积分损失略有增加",
    "Slightly increased HQ items prices": "总部物品价格小幅上涨",
    "Slightly increased Keyboard and Mouse bonus effect from online store": "略微增加了在线商店的键盘和鼠标奖励效果",
    "Slightly increased Online items prices": "线上商品价格小幅上涨",
    "Slightly increased Online items sizes": "略微增加在线商品尺寸",
    "Software page in expanded System Manager now shows the current software's effect": "扩展系统管理器中的软件页面现在显示当前软件的效果",
    "Some visual have been removed and some have been repositioned": "一些视觉效果已被删除，一些已重新定位",
    "The old G.A.I.A sabotage mechanic proved to be more frustrating than creating a challenge, and it comes with design flaws, so here's the new sabotage mechanic: When Hacked by G.A.I.A": "事实证明，旧的 G.A.I.A 破坏机制比创造挑战更令人沮丧，而且它存在设计缺陷，所以这是新的破坏机制：当被 G.A.I.A 黑客攻击时",
    "Updated all pop-up tutorials texts to fit the new style": "更新了所有弹出教程文本以适应新风格",
    "With the introduction of the new effects system, fixed Crown coins animation and effects gets buggy if Crown coin taken by normal method then from Gift AD sequanthally": "随着新效果系统的引入，修复了如果通过正常方法获取皇冠币然后从礼物 AD 中获取皇冠币的话，固定的皇冠币动画和效果会出现问题",
    "With the introduction of the new UI, all old bugs related to menus such as unable to resize, reposition, or contents out of boundaries, all are now irrelevant to this new UI": "随着新 UI 的引入，所有与菜单相关的旧错误（例如无法调整大小、重新定位或内容超出边界）现在都与此新 UI 无关",
    "With the introduction of the new UI, scroll bars can now be added without breaking anything": "随着新 UI 的引入，现在可以添加滚动条而不会破坏任何内容",
    "You can now double click save file to start the game": "您现在可以双击保存文件来开始游戏",
    "You can now expand System manager menu to get detailed information about the system": "您现在可以展开系统管理器菜单来获取有关系统的详细信息",
    "> Welcome back Agent.": "> 欢迎回来代理。",
    "Press L: 16. Next: K": "按 L：16。下一个：K",
    "> Changed to 'Addition' Task on Easy mode": "> 更改为简单模式下的“加法”任务",
    "> Changed to 'Sequence' Task on Easy mode": "> 更改为简单模式下的“顺序”任务",
    "A Task given by HQ": "总部交给的任务",
    "Addition": "加法",
    "Contribution progression": "贡献进展",
    "Correctly enter given arrow sequence using keyboard arrows keys": "使用键盘箭头键正确输入给定的箭头顺序",
    "Get Rewards from HQ when collecting 10, 25, 40, 55, and 100 Contribution points": "累积10、25、40、55、100点贡献值即可获得总部奖励",
    "In HQ store, you can buy CPU, GPU, RAM, or FAN, these items will help you extend System's resources power, be careful as they all share same price, so only buy what is needed the most": "在总部商店，你可以购买CPU、GPU、RAM或FAN，这些物品将帮助你扩展系统的资源能力，要小心，因为它们的价格相同，所以只买最需要的东西",
    "Item Price: ": "商品价格：",
    "Pasue/Resume": "暂停/恢复",
    "Pause/Resume button, to receive inputs towards tasks or not": "暂停/恢复按钮，用于接收或不接收任务输入",
    "Repeatedly press requested keyboard key x amount of times": "重复按请求的键盘按键 x 次",
    "Shows current Contribution points progression for the next HQ Contribution reward": "显示下一个总部贡献奖励的当前贡献点数进度",
    "Solve given Addition problems and find the value of (?) where its presented": "解决给定的加法问题并找到 (?) 出现的值",
    "Unable to connect to \"Online Store": "无法连接到“在线商店”",
    "When paused, inputs will not be counted towards tasks progression": "暂停时，输入将不计入任务进度",
    "you need at least 1 Router installed": "您至少需要安装 1 个路由器",
    "stable": "稳定",
    "Heat should be balanced between 0": "热量应在 0 之间平衡",
    "> Changed to 'Pressing' Task on Normal mode": "> 更改为正常模式下的“按下”任务",
    "Advanced Casting tong": "高级铸造钳",
    "Advanced Casting tong used in Casting activities with x6.25 efficiency": "先进的铸造钳用于铸造活动，效率 x6.25",
    "Advanced Explorer bot": "高级探索者机器人",
    "Advanced Explorer bot used in Exploring activities with x6.25 efficiency": "用于探索活动的高级 探索 机器人，效率为 x6.25",
    "Advanced Mining bot": "先进的挖矿机器人",
    "Advanced Mining bot used in Mining activities with x6.25 efficiency": "用于采矿活动的高级采矿机器人，效率为 x6.25",
    "Advanced Recycling bot": "先进的回收机器人",
    "Advanced Recycling bot used in Recycling activities with x6.25 efficiency": "用于回收活动的高级回收机器人，效率为 x6.25",
    "Advanced Scrap Grapple": "先进的废料抓斗",
    "Advanced Scrap Grapple used in Scrapping activities with x6.25 efficiency": "先进的废料抓斗用于废料活动，效率为 x6.25",
    "Advanced Support Hand": "高级支援手",
    "Advanced Support Hand used in Procedure activities with x6.25 efficiency": "高级支持手用于程序活动，效率为 x6.25",
    "Anable to start AD,": "能够启动AD，",
    "Assembling a bot require Materials, to assemble a bot, click on its icon": "组装机器人需要材料，要组装机器人，请单击其图标",
    "Automation bots require Energy to function, while other types do not. Bots stats are Energy, Hit points, Fire power, and Cargo capacity": "自动化机器人需要能量才能发挥作用，而其他类型则不需要。 机器人统计数据包括能量、生命值、火力和货物容量",
    "Bot manager": "机器人管理",
    "CPU is required for everything, mainly for softwares, keep CPU under 100% to decode data at max speed": "一切都需要 CPU，主要是软件，将 CPU 保持在 100% 以下，以最大速度解码数据",
    "CPU is stable": "CPU稳定",
    "CPU usage": "CPU使用率",
    "Crack Password": "破解密码",
    "Credit is used to buy all kindes of wares": "积分用于购买各种商品",
    "Data is used to research new technologies": "数据用于研究新技术",
    "Decoded Data": "解码数据",
    "download /[PATH_TO_DESIRED_FILES] [LOCAL_DIRECTORY]": "下载 /[PATH_TO_DESIRED_FILES] [LOCAL_DIRECTORY]",
    "Easy mode": "简易模式",
    "Easy Pressing Tasks:": "简单的紧迫任务：",
    "echo \"Blocking known attacking IP addresses...\"": "echo \“阻止已知的攻击IP地址...”",
    "echo \"Brute-forcing login credentials using ncrack...\"": "echo \“使用 ncrack 强制登录凭据...\”",
    "echo \"Checking for incoming attacks...\"": "echo \“正在检查传入的攻击...”",
    "echo \"Covering tracks and exiting target system...\"": "echo \“覆盖轨迹并退出目标系统...”",
    "echo \"Downloading desired files from target system...\"": "echo \“从目标系统下载所需的文件...”",
    "echo \"Enabling firewall to protect against further attacks...\"": "echo \“启用防火墙以防止进一步的攻击...”",
    "echo \"Escalating privileges to gain root access...\"": "echo \“升级权限以获取 root 访问权限...”",
    "echo \"Sabotaging targets data...\"": "echo \“破坏目标数据...”",
    "echo \"Scanning target system for open ports...\"": "echo \“正在扫描目标系统的开放端口...”",
    "echo \"Searching for desired files on target system...\"": "echo \“正在目标系统上搜索所需的文件...\”",
    "Energy is required when assigning bots, gain +1 Energy for each Solar power, and +3 for each Magnetic generator Hardwares": "分配机器人时需要能量，每个太阳能获得 +1 能量，每个磁力发电机获得 +3 能量",
    "exit": "出口",
    "Fine Casting tong": "精铸钳",
    "Fine Casting tong used in Casting activities with x2.5 efficiency": "精铸钳用于铸造活动，效率 x2.5",
    "Fine Explorer bot": "精细探索者机器人",
    "Fine Explorer bot used in Exploring activities with x2.5 efficiency": "Fine Explorer 机器人用于探索活动，效率提高 2.5 倍",
    "Fine Mining bot": "精细挖矿机器人",
    "Fine Mining bot used in Mining activities with x2.5 efficiency": "Fine Mining bot 用于采矿活动，效率为 x2.5",
    "Fine Recycling bot": "精细回收机器人",
    "Fine Recycling bot used in Recycling activities with x2.5 efficiency": "Fine Recycling 机器人用于回收活动，效率为 x2.5",
    "Fine Scrap Grapple": "细废钢抓斗",
    "Fine Scrap Grapple used in Scrapping activities with x2.5 efficiency": "用于报废活动的精细废料抓斗，效率为 x2.5",
    "Fine Support Hand": "精细支撑手",
    "Fine Support Hand used in Procedure activities with x2.5 efficiency": "精细支撑手用于程序活动，效率为 x2.5",
    "G.A.I.A difficulity increases frequency of Hack attempts, sobatage effect and duration": "G.A.I.A 难度会增加黑客尝试的频率、破坏效果和持续时间",
    "G.A.I.A status": "G.A.I.A 状态",
    "GPU is required for everything, mainly for generating Credit, keep GPU under 100% to generate at max speed": "一切都需要 GPU，主要是为了生成 Credit，将 GPU 保持在 100% 以下以最大速度生成",
    "GPU is stable": "GPU稳定",
    "Hard mode": "困难模式",
    "Hard Pressing Tasks:": "艰巨的任务：",
    "Heat status": "热度状态",
    "Insufficient credit": "积分不足",
    "Materials is used to assumble new bots": "材料用于组装新机器人",
    "Network speed is how fast you can download from the Network": "网络速度是指您从网络下载的速度",
    "Normal mode": "正常模式",
    "Normal Pressing Tasks:": "正常的压制任务：",
    "Password:": "密码：",
    "RAM is required for installing all kinds of new wares": "安装各种新软件都需要RAM",
    "RAM space is avaliable": "RAM 空间可用",
    "Regular Casting tong": "普通铸造钳",
    "Regular Casting tong used in Casting activities": "铸造活动中使用的常规铸造钳",
    "Regular Explorer bot": "常规探索者机器人",
    "Regular Explorer bot used in Exploring activities": "探索活动中使用的常规探索者机器人",
    "Regular Mining bot": "常规挖矿机器人",
    "Regular Mining bot used in Mining activities": "采矿活动中使用的常规采矿机器人",
    "Regular Recycling bot": "常规回收机器人",
    "Regular Recycling bot used in Recycling activities": "回收活动中使用的常规回收机器人",
    "Regular Scrap Grapple": "常规废料抓斗",
    "Regular Scrap Grapple used in Scrapping activities": "报废活动中使用的常规废料抓斗",
    "Regular Support Hand": "常规支援手",
    "Regular Support Hand used in Procedure activities": "程序活动中使用的常规支持手",
    "Reset contribution points progression to 0": "将贡献点进度重置为0",
    "Same key will not be requested in a row": "不会连续请求相同的密钥",
    "Solve given problems to crack the password": "解决给定的问题来破解密码",
    "something went wrong!": "出了些问题！",
    "Tasks on Easy mode give:": "简单模式下的任务给出：",
    "Tasks on Hard mode give:": "困难模式下的任务给出：",
    "Tasks on Normal mode give:": "正常模式下的任务给出：",
    "Tiers reset": "等级重置",
    "to avoid Hardwares failures": "以避免硬件故障",
    "ufw enable": "ufw 启用",
    "Watch": "观看",
    "Watch AD to Get x1 keyboard?": "观看 AD 以获得 x1 键盘？",
    "When Energy consumption is greater than Max Energy, all assigned bots will stop working": "当能量消耗大于最大能量时，所有分配的机器人将停止工作",
    "When resetting, all Tiers rewards will be recalculated to the current scale": "重置时，所有等级奖励将重新计算至当前规模",
    "When Threat reaches 100%, G.A.I.A will take control over the System, blocking access to it": "当威胁达到 100% 时，G.A.I.A 将控制系统，阻止对其的访问",
    "World map will be implemented in next updates": "世界地图将在下次更新中实现",
    "Registering new user into the": "注册新用户进入",
    "> Idle...": "> 空闲...",
    "A.I Network in order to find a way to erase it once and for good and save the world": "A.I 网络 为了找到一种方法，一劳永逸地消除它并拯救世界",
    "All kinds of messages will be desplayed here, keep track of all messages from the System or from other sources": "各种消息都会显示在这里，跟踪来自系统或其他来源的所有消息",
    "Blocked Hacks": "阻止黑客攻击",
    "Contribution Rewards have been updated": "贡献奖励已更新",
    "Generated Credit": "产生的积分",
    "Idle for": "放置时长",
    "is an A.I that was built to help manage World resources, but things got out of control so fast, and the A.I considered us (Humans) as a resources too": "是一个人工智能，旨在帮助管理世界资源，但事情很快就失去控制，人工智能也将我们（人类）视为一种资源",
    "Keep up the good work Agent, further information will be given soon": "继续努力代理，更多信息将很快提供",
    "Produced Materials": "生产材料",
    "Registering new user into the": "将新用户注册到",
    "started to eliminate Humans, and it took control over everything in order to fulfill its main goal, which is to find balance": "开始消灭人类，并控制一切以实现其主要目标，即寻找平衡",
    "Succesfull Hacks": "成功的黑客",
    "This system will decode Data mined from": "该系统将解码从中挖掘的数据",
    "Threat": "威胁",
    "Unauthorized Machine detected, Install your R certificate, or legal actions will be taken against you": "检测到未经授权的机器，请安装您的 R 证书，否则将对您采取法律行动",
    "Welcome to the crew Agent, do not be afraid of that warning message": "欢迎加入船员代理，不要害怕那个警告信息",
    "While in Idle state, G.A.I.A will continue its HACK attempts, 'Auto block' is automatically activated, HACK block is based on Firewall's block chance rate": "在空闲状态下，G.A.I.A 将继续其 HACK 尝试，自动激活“自动阻止”，HACK 阻止基于防火墙的阻止几率",
    "will attempt to Hack the System continuously to take control over it, your job is to keep this system running for as long as possible": "将尝试不断入侵系统以控制它，你的工作是让该系统尽可能长时间地运行",
    "Insufficient materials": "材料不足",
    "No effects currently active": "当前没有激活的效果",
    "Warehouse is where all assembled bots are, keep track of each bot type individually": "仓库是所有组装的机器人所在的地方，单独跟踪每个机器人类型",
    "1M credit a second, keeps the doctor away": "每秒1M积分，让医生远离我",
    "3 days and 3 nights": "3天3夜",
    "3D NAND Flash Memory": "3D NAND闪存",
    "3D XPoint Memory": "3D XPoint 内存",
    "A job to be done": "有待完成的工作",
    "A third of a year": "一年三分之一",
    "A.I. integrated chair": "人工智能。 一体式椅子",
    "A.I. integrated Computers": "人工智能。 集成计算机",
    "A.I. integrated Desk": "人工智能。 综合办公桌",
    "A.I. integrated Magnatic generator": "人工智能。 集成磁力发电机",
    "A.I. integrated Monitor": "人工智能。 集成监控器",
    "A.I. integrated Radar dish": "人工智能。 集成雷达天线",
    "A.I. integrated Radio tower": "人工智能。 综合无线电塔",
    "A.I. integrated Router": "人工智能。 集成路由器",
    "A.I. integrated Satellites": "人工智能。 综合卫星",
    "A.I. integrated Solar panels": "人工智能。 集成太阳能电池板",
    "ab-naire?": "阿布奈尔？",
    "Accelerated thinking": "加速思考",
    "Accomplished finely": "完成得很好",
    "ADDiction!": "瘾！",
    "Addition and money, i can do both": "加法和金钱，我都可以做",
    "Addition is awesome": "加法太棒了",
    "ADDmatician?": "ADD科学家？",
    "All according to what's required": "一切按照要求进行",
    "Almost Golden": "几乎金色",
    "AM Radio": "调幅收音机",
    "AMOLED Monitor": "AMOLED显示器",
    "Any bit can be the key": "任何一点都可以是关键",
    "Assembly": "集会",
    "At night, i see it move by its own, something is not right!": "到了晚上，我看见它自己动了，有什么不对劲！",
    "Basic arithmetic operation expert": "基础算术运算专家",
    "Be careful, achieving much might puts you on G.A.I.A's balancing list": "小心，取得很多成就可能会让你进入 G.A.I.A 的平衡名单",
    "Beyond and further economist": "超越和进一步的经济学家",
    "Big System": "大系统",
    "Billionaire": "亿万富翁",
    "Billions and Billions...": "数十亿、数十亿……",
    "Binary Language": "二进制语言",
    "bittersweet": "苦乐参半",
    "Board": "木板",
    "Brain training": "大脑训练",
    "Browsing the store": "浏览商店",
    "Business man": "商人",
    "C/C++/Java...": "C/C++/Java...",
    "Cache Memory": "高速缓存存储器",
    "Central communication streamline": "中央通讯简化",
    "Certain someone would love this tasks": "某些人会喜欢这个任务",
    "Check list": "检查清单",
    "Check on your mouse": "检查你的鼠标",
    "Click and get paid": "点击并获得报酬",
    "Click Click Click": "点击 点击 点击",
    "Clicker Bot": "Clicker 机器人",
    "Clicker economist": "点击经济学家",
    "Coding Design Patterns": "编码设计模式",
    "Computers factory": "电脑厂",
    "Continental System": "大陆系统",
    "Cosmic frequency detection": "宇宙频率探测",
    "Cosmic Observer": "宇宙观察者",
    "Country reconnaissance": "国家侦察",
    "Country Surveillance": "国家监控",
    "Credits?, sign me in": "积分？，让我登录",
    "CRT Monitor": "显像管显示器",
    "Data is money": "数据就是金钱",
    "Data Lakes": "数据湖",
    "Data phishing": "数据网络钓鱼",
    "Data Silos": "数据孤岛",
    "Data Transaction": "数据交易",
    "Data worm": "数据蠕虫",
    "Dataaholic": "数据狂",
    "Delay Line Memory": "延迟线记忆",
    "Desk with a bed": "书桌和床",
    "Desk with a fridge": "带冰箱的书桌",
    "Desk with drawers": "带抽屉的书桌",
    "Desks are real estate now": "办公桌现在是房地产",
    "Detection Mesh": "检测网",
    "Detection of everything": "检测一切",
    "Diamond customer": "钻石客户",
    "Did i get faster using the keyboard?": "我使用键盘变得更快了吗？",
    "Dimensional economist": "维度经济学家",
    "Disguised transferation": "变相转让",
    "Double Mouse???": "双鼠标？？？",
    "DRAM": "动态随机存取存储器",
    "Easiest job": "最简单的工作",
    "Electricity company": "电力公司",
    "Electricity institution": "电力机构",
    "Electromagnet Expert": "电磁铁专家",
    "Electromagnetic compatibility": "电磁兼容",
    "Electromagnetic induction": "电磁感应",
    "Electrostatic Storage": "静电存储",
    "Endless Bottom cart": "无尽底推车",
    "Endless regret": "无尽的遗憾",
    "Energy distribution": "能源分配",
    "Energy producer": "能源生产商",
    "Ethereal Signal collector": "空灵信号采集器",
    "Ever heard of a chair that tells you to get up?": "你听说过有一把椅子可以叫你起床吗？",
    "Everyone is happy": "大家都开心",
    "Expert clicker": "专家答题器",
    "Eye tracking mouse": "眼动追踪鼠标",
    "Fast fingers": "快速的手指",
    "Feels like it's not worth it": "感觉不值得",
    "Fighting requires commitment": "战斗需要承诺",
    "Final solution, where is the hammer?": "最终解决办法，锤子在哪里？",
    "First hour": "第一个小时",
    "First paycheck": "第一份薪水",
    "Flash Memory": "闪存",
    "Floor is your Desk": "地板就是你的办公桌",
    "FM Radio": "调频收音机",
    "Free energy": "自由能",
    "Full house Desk": "全屋办公桌",
    "G.A.I.S's system is not complete": "G.A.I.S的系统并不完整",
    "Galactic economist": "银河经济学家",
    "Gaming Chair": "电竞椅",
    "Gaming Router": "游戏路由器",
    "Gateway": "网关",
    "Generative": "生成式",
    "Generative hands": "富有创造力的双手",
    "Getting it right": "正确处理",
    "Getting paied": "获得报酬",
    "Getting paied for pressing buttons": "按下按钮即可获得报酬",
    "Giga worth of tasks": "价值数十亿的任务",
    "Global economist": "全球经济学家",
    "Global System": "全球系统",
    "Golden customer": "黄金客户",
    "Golden finger": "金手指",
    "Good job, you did it": "干得好，你做到了",
    "Hard worker": "勤劳的人",
    "Heart reading mouse": "读心鼠标",
    "High-level Languages": "高级语言",
    "Hive mind": "蜂群思维",
    "Hologram Desk": "全息办公桌",
    "Hologram Monitor": "全息监视器",
    "Holographic wave Imaging": "全息波成像",
    "Home Router": "家庭路由器",
    "How do i command it to stop following me!?": "我该如何命令它停止跟踪我！？",
    "HQ's reliable agent": "总部可靠的代理",
    "Huge System": "庞大的系统",
    "Human ADDculator": "人类ADD计算器",
    "I am investing my money to improve Earth": "我正在投资我的钱来改善地球",
    "I am reducing my resources consumption": "我正在减少资源消耗",
    "I can buy myself a planet": "我可以给自己买一个星球",
    "I can do Addition": "我可以做加法",
    "I can just sit here and it will do everything for me!": "我只需坐在这里，它就会为我做一切！",
    "I have so much money i don't know what to do with it": "我有这么多钱我不知道该做什么",
    "I invested money to improve Earth": "我投资了钱来改善地球",
    "I know what 377 + 733 is": "我知道 377 + 733 是什么",
    "I pay, things get done!": "我付钱，事情就完成了！",
    "I think it's broken!": "我觉得它坏了！",
    "If you do not exist, then you can't be on G.A.I.A's balancing list": "如果你不存在，那么你就不能出现在 G.A.I.A 的平衡名单上",
    "Imagine owning Trillions in 64bits only...": "想象一下仅 64 位就拥有数万亿美元......",
    "In Achievements menu, you can keep track of your progress across different parts, On each milestone, you gain bonus CPS": "在成就菜单中，您可以跟踪不同部分的进度，在每个里程碑上，您都会获得奖励 CPS",
    "In digital economy, Data is everything": "数字经济，数据就是一切",
    "In digital economy, you can alway bypass": "数字经济时代，你总能绕过",
    "Intermediate data miner": "中级数据挖掘者",
    "International economist": "国际经济学家",
    "International System": "国际体系",
    "Internet of things": "物联网",
    "Interstellar Dish": "星际碟",
    "Interstellar navigator": "星际航行者",
    "Into the realm of Wealth": "进入财富领域",
    "Is this real?": "这是真的吗？",
    "It doesn't matter to be right, it needs to be all 4 directions": "正确与否并不重要，4个方向都需要",
    "It is too good to be true": "好得令人难以置信",
    "It never ends": "它永远不会结束",
    "It was a bad idea to install A.I. in chairs": "安装人工智能是个坏主意。 在椅子上",
    "It's already done sir": "先生已经办好了",
    "It's night time, yet they are moving!": "已经是晚上了，他们却在行动！",
    "It's running unknown Tasks!": "它正在运行未知的任务！",
    "Its saying its first word...": "它说出了第一个词……",
    "Jack of all trades": "万事通",
    "Job done": "任务完成",
    "Junior data miner": "初级数据挖掘者",
    "Just don't spend it in a suspicious way": "只是不要以可疑的方式花费它",
    "Just keep adding names and you will be fine": "只要继续添加名字就可以了",
    "Just one more to gain more": "只要再多一份，就能收获更多",
    "Just Transistors": "只是晶体管",
    "Keep clicking": "继续点击",
    "Keep it on": "继续",
    "Keeping my attendance": "保持我的出勤率",
    "Key": "钥匙",
    "Keyboard True": "键盘真",
    "Keyboard True Max": "键盘真实最大",
    "Keyboard True Max X": "键盘 真实最大 X",
    "Keyboard True Max X Ultra": "键盘 真实最大 X 超级",
    "Keyboard True Max X Ultra Ultimate": "键盘 真实最大 X 终极",
    "Keyboard True Max X Ultra Ultimate Definitive": "键盘 真实最大 X 超终极",
    "Keys and Boards": "按键和主板",
    "L shaped Desk": "L型办公桌",
    "Large System": "大型系统",
    "Lasagna Code": "千层面代码",
    "LCD Monitor": "液晶显示器",
    "LED Monitor": "LED监视器",
    "Looking for more pressing tasks": "寻找更紧迫的任务",
    "Looking for new way to spend money on": "寻找新的花钱方式",
    "Loosing my mind": "失去我的理智",
    "Low-level Languages": "低级语言",
    "Machine Language": "机器语言",
    "Magnetic Core Memory": "磁芯存储器",
    "Magnetic Disk Storage": "磁盘存储",
    "Magnetic Drum Memory": "磁鼓记忆",
    "Magneto-Optical Disc": "磁光盘",
    "Main spyware": "主要间谍软件",
    "Mainframe computers": "大型计算机",
    "Making money by clicking": "点击赚钱",
    "Making sure the mouse is working": "确保鼠标正常工作",
    "Making sure the program is working": "确保程序正常运行",
    "Massive budget, but I got this": "预算很大，但我得到了这个",
    "Massive System": "海量系统",
    "Mediocre System": "平庸的系统",
    "Mega decoder": "兆丰解码器",
    "Microcomputers": "微型计算机",
    "Mind reading mouse": "读心鼠标",
    "Mini System": "迷你系统",
    "Minicomputers": "小型机",
    "Money circulation": "货币流通",
    "Monitor that watches you instead": "监视你的监视器",
    "Monitor with a camera": "用摄像头监控",
    "Monitoring room": "监控室",
    "More than enough": "绰绰有余",
    "MOS Memory": "MOS内存",
    "Mouse that have its own conscious": "有自己意识的老鼠",
    "Moveable Desk": "移动办公桌",
    "Multidimensional economist": "多维经济学家",
    "Multiverse economist": "多元宇宙经济学家",
    "Must be in this order": "必须按照这个顺序",
    "NAND Flash Memory": "NAND闪存",
    "Nanosoft": "纳米软件",
    "Natural Numbers": "自然数",
    "Never complaining": "从不抱怨",
    "Never ending dream": "永无止境的梦想",
    "No Data about you?, then you do not exist": "没有关于你的数据？，那么你不存在",
    "North magnetic pole": "北磁极",
    "Not giving up": "不放弃",
    "Not letting go": "不放手",
    "Nothing is perfect": "没有什么是完美的",
    "Observation Mesh": "观察网",
    "Office Chair": "办公椅",
    "Ok, seriously how did you not get investigated?": "好吧，说真的，你怎么没有被调查？",
    "OLED Monitor": "有机发光二极管显示器",
    "Once the system is down, all these Credits means nothing": "一旦系统崩溃，所有这些积分就毫无意义",
    "One of each item please": "请每件一件",
    "Paied in Data": "付费数据",
    "Part of my routine": "我日常工作的一部分",
    "PC Company": "电脑公司",
    "Phase Change Memory": "相变存储器",
    "Photovoltaic effect": "光伏效应",
    "Planetary economist": "行星经济学家",
    "Planetary System": "行星系统",
    "Plastic Chair": "塑料椅",
    "Power Grid": "电网",
    "Power leakage": "漏电",
    "Powering it": "为其供电",
    "Press everything": "按一切",
    "Press everywhere": "到处按",
    "Press that": "按那个",
    "Press this": "按此",
    "Press, sleep, repeat": "按、睡眠、重复",
    "Pressing expert": "压制专家",
    "Pressing is my life": "压力就是我的生活",
    "Pressing machine": "压合机",
    "Pressing maneuver": "按压动作",
    "Professional clicker": "专业答题器",
    "Purely sequential": "纯顺序的",
    "Pursuing a goal": "追求一个目标",
    "Pushing through pain": "克服痛苦",
    "Quadrillionaire": "四亿富翁",
    "Radio brodcasting": "广播",
    "RAdio Detection And Ranging": "无线电探测和测距",
    "Regional economist": "区域经济学家",
    "Regional reconnaissance": "区域侦察",
    "Regional Surveillance": "区域监控",
    "Regularity": "规律性",
    "Revolutionary communication": "革命性的沟通",
    "Rock Desk": "摇滚桌",
    "Router with four Antennas": "带四个天线的路由器",
    "Router with three Antennas": "带三个天线的路由器",
    "Router with two Antennas": "带两个天线的路由器",
    "Satellite Interceptor": "卫星拦截器",
    "Scientist have developed a system that will help": "科学家开发了一个系统，可以帮助",
    "Searching for G.A.I.A's traces": "寻找G.A.I.A的踪迹",
    "Self positioning mouse, for lazy people": "自定位鼠标，适合懒人",
    "Senior data miner": "资深数据挖掘师",
    "Sequence motif": "顺序基序",
    "Sequence specialist": "顺序专家",
    "Sequences can be found anywhere": "顺序可以在任何地方找到",
    "Sequential execution": "顺序执行",
    "Sequentially without emotions": "依次无情绪",
    "Shareholder": "股东",
    "Sharing it to other people": "分享给其他人",
    "Shopping": "购物",
    "Shopping addict": "购物狂",
    "Shopping spree": "疯狂购物",
    "SIMULA": "模拟",
    "Sky eyes": "天眼",
    "Sky is the only limit": "天空是唯一的限制",
    "Small System": "小型系统",
    "Smart Chair": "智能椅",
    "Smart Monitor": "智能监控",
    "So many things to buy": "这么多东西要买",
    "So this System is running on what?": "那么这个系统运行在什么之上呢？",
    "Social media clone": "社交媒体克隆",
    "Software engineer": "软件工程师",
    "Solar panels grid": "太阳能电池板网格",
    "Solar Pioneer": "太阳能先锋",
    "Solar Sage": "太阳能圣人",
    "Solar Sentinel": "太阳哨兵",
    "Solar Sustainer": "太阳能支架",
    "Solar system": "太阳系",
    "Solve from left to right": "从左到右解决",
    "Solveing problems faster, i can feel it": "更快地解决问题，我能感觉到",
    "Someone is watching me, i can feel it": "有人在看着我，我能感觉到",
    "Soul reading mouse": "灵魂阅读鼠标",
    "Spaghetti Code": "意大利面条代码",
    "Spending without regrets": "消费无悔",
    "SSDs": "固态硬盘",
    "STANLEY would be proud of you": "斯坦利会为你感到骄傲",
    "Static RAM": "静态内存",
    "Still not detected": "仍未检测到",
    "Stop asking me how i did it, ask who program it...": "别问我是怎么做到的，问问是谁编程的......",
    "Storage Class Memory": "存储级内存",
    "Sun bro": "孙哥",
    "Sun energy": "太阳能",
    "Sun tracking solar panels": "太阳跟踪太阳能电池板",
    "Super System": "超级系统",
    "Supercomputers": "超级计算机",
    "Synchronous Dynamic RAM": "同步动态RAM",
    "Tape Storage": "磁带存储",
    "Task commitment": "任务承诺",
    "Taskaholic": "任务狂",
    "Tasks bot": "任务机器人",
    "Testing my limit": "测试我的极限",
    "Testing my patience": "考验我的耐心",
    "Thank you for your patronage": "谢谢您的光顾",
    "The chair is resisting!": "椅子在反抗！",
    "The favourite customer": "最喜欢的顾客",
    "The Internet": "互联网",
    "The results are good": "结果很好",
    "The right man for any task": "适合任何任务的合适人选",
    "The system is doing far more then it should be.": "该系统所做的远远超出了应有的程度。",
    "Thin Film Memory": "薄膜存储器",
    "Things going great": "事情进展顺利",
    "This chair is out of control!": "这把椅子失控了！",
    "This Router choose best paths as needed, Amazing": "这个路由器根据需要选择最佳路径，太神奇了",
    "This Router knows about me more than my mother...": "这个路由器比我妈妈还了解我......",
    "Time is running": "时间正在流逝",
    "Tiny System": "微型系统",
    "™ © MangoFlavor, 2024": "™ © 芒果味，2024",
    "Todo List": "待办事项清单",
    "Too many Keys and Boards": "按键和板太多",
    "Too many names to be displayed": "太多名字无法显示",
    "Torsion Wire Memory": "扭力线记忆",
    "Touch Desk": "触摸桌",
    "Touch Monitor": "触摸显示器",
    "Trainee data miner": "实习数据挖掘员",
    "Transmission Balancing": "传输平衡",
    "Tunneling all apps...": "正在为所有应用程序建立隧道...",
    "Two ways connection": "两种连接方式",
    "Universal economist": "普世经济学家",
    "Universal Messenger": "通用信使",
    "Universal Wave Network": "环球波网",
    "Unknown consumption": "消费未知",
    "Unknown heights": "未知的高度",
    "Unlimited speed Router, or so they say...": "无限速路由器，或者他们这么说......",
    "Unnatural condensed observation": "不自然的浓缩观察",
    "up, up, down, down, left, right, left, right, B, A": "上、上、下、下、左、右、左、右、B、A",
    "Virtual memory": "虚拟内存",
    "Wait, this Mouse is talking?": "等等，这只老鼠在说话？",
    "We are firnds now": "我们现在是朋友了",
    "What is better than 1M?, 100M": "比1M、100M哪个更好",
    "What is this Network that this router keep conecting to?": "该路由器保持连接的网络是什么？",
    "What lies in the Unknown economist": "《未知的经济学家》中隐藏着什么",
    "What lies in what we can't know economist": "经济学里有什么是我们不知道的",
    "What time it is?, it's CLICKING time": "现在几点了？点击时间到了",
    "What you take will return": "你所拿走的，终将归还",
    "Wheelchair": "轮椅",
    "When problems get solved, new ones replace them": "当问题解决后，新的问题就会取代它们",
    "Wherever you go, there are happy faces": "无论走到哪里，都是幸福的面孔",
    "Who he is above the laws": "他是谁，凌驾于法律之上",
    "Whole Numbers": "整数",
    "WIFI Router": "WIFI路由器",
    "Williams Tube": "威廉斯管道",
    "Wooden Chair": "木椅",
    "Wooden Desk": "木书桌",
    "Work in sequence or importance?": "工作的顺序或重要性？",
    "World hunger is almost a myth": "世界饥饿几乎是一个神话",
    "World wide reconnaissance": "全球侦察",
    "World wide Surveillance": "全球监控",
    "Yep, they are working": "是的，他们正在工作",
    "Yet, Spaghetti Pattern is the dominant": "然而，意大利面条图案是主导",
    "You and G.A.I.A might become friends": "你和 G.A.I.A 可能会成为朋友",
    "> Changed to 'Pressing' Task on Hard mode": "> 更改为困难模式下的“按下”任务",
    "Normal Addition Tasks:": "正常添加任务：",
    "Solve for 2 digits numbers": "求解 2 位数字",
    "Watch AD to get ×2 CPS Multiplier for 10 minutes?": "观看 AD 以获得 ×2 CPS 乘数 10 分钟？",
    "> Installed 1 Keyboard": "> 已安装1个键盘",
    "Click here to generate Credit": "单击此处生成积分",
    "CPU, GPU, RAM, and Heat are the main 4 resources, keep all of them in a good balance for maximum performance": "CPU、GPU、RAM 和热量是主要的 4 种资源，保持它们之间的良好平衡以获得最大性能",
    "Here you can Keep track of all resources and their status, be careful, low resources will lead to poor System performance": "在这里您可以跟踪所有资源及其状态，小心，资源不足会导致系统性能不佳",
    "Insufficient contribution points": "贡献点不足",
    "Keep track of all currently applied effects here. Click here to pin the effects list to be able to scroll the list if needed": "在这里跟踪所有当前应用的效果。 单击此处固定效果列表，以便能够根据需要滚动列表",
    "Keyboards are twice as efficient": "键盘效率提高一倍",
    "On collecting 10, 25, 40, 55, or 100 contribution points, you can collect bigger rewards from HQ, these rewards are repeatable for as long as you do Tasks": "收集10、25、40、55、100点贡献点，即可从总部领取更大的奖励，这些奖励只要你做任务就可以重复获得",
    "Online store CPU usage: 0%": "在线商店 CPU 使用率：0%",
    "Softwares will unlock automatically while progressing, buying Softwares will updrade different functionalities of the System": "软件在进行过程中会自动解锁，购买软件会升级系统的不同功能",
    "Tasks are optional way for earning Credit or Data, choose a Task and set the difficulty then start completing them": "任务是赚取积分或数据的可选方式，选择一个任务并设置难度，然后开始完成它们",
    "To Buy Hardwares you need Credit currency, buying Hardwares will increase your CPS (Credit Per Second). Some Hardwares enhance other functionalities of the System": "要购买硬件，您需要信用货币，购买硬件将增加您的 CPS（每秒信用数）。 一些硬件增强了系统的其他功能",
    "Toggle between Resum/Pause to indicate whether inputs should be counted as Tasks inputs or not": "在恢复/暂停之间切换以指示输入是否应计为任务输入",
    "Watch Ads here and get rewarded, either with global CPS/global DPS Multipliers, or with other items, Please disable AD blocker if you want to benefit from it": "在这里观看广告并获得奖励，无论是全球 CPS/全球 DPS 乘数，还是其他物品，如果您想从中受益，请禁用广告拦截器",
    "When Heat reaches 95+℃ or 0-℃, the System will be overheated/over-cooled, causing one random Hardware to fail for every interval, keep heat balanced": "当热量达到95+℃或0-℃时，系统将过热/过冷，导致每个时间间隔有一个随机硬件出现故障，保持热量平衡",
    "> Addition Task complated,": "> 添加任务已完成，",
    "> Addition Task,": "> 添加任务，",
    "> Pressing Task complated,": "> 按下任务已完成，",
    "> Pressing Task,": "> 按下任务，",
    "> Sequence Task complated,": "> 顺序任务已完成，",
    "> Sequence Task,": "> 顺序任务，",
    "Contribution.": "贡献。",
    "credit": "信用",
    "Hard Addition Tasks:": "硬加法任务：",
    "Hard Sequence Tasks:": "硬顺序任务：",
    "Incorrect answer": "不正确的答案",
    "Incorrect input": "输入错误",
    "Incorrect sequence": "顺序错误",
    "Normal Sequence Tasks:": "正常顺序任务：",
    "Solve for 3 digits numbers": "求解 3 位数字",
    "Clicks are twice as efficient": "点击效率提高一倍",
    "Mouses are twice as efficient": "鼠标效率提高一倍",
    "When Threat reaches 100% while in Idle, the System will be Locked by G.A.I.A, and all resources will stop generating": "当空闲时威胁达到100%时，系统将被G.A.I.A锁定，所有资源将停止生成",
    "While in Idle state, Heat will not effect the system and it will not rise or cooldown, and the System will continue to generate resources normally": "在空闲状态下，热量不会影响系统，不会上升或冷却，系统将继续正常生成资源",
    "> Turned on Auto install, changed to Automaticcaly Install Softwares": "> 开启自动安装，改为自动安装软件",
    "> Turned off Auto install, changed to Manually Installing Softwares": "> 关闭自动安装，改为手动安装软件",
    "> Turned on Auto block, changed to Auto defending against Hack attempts based on Firewall block chance rate": "> 开启自动拦截，改为根据防火墙拦截几率自动防御黑客尝试",
    "System manager": "系统管理",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "qh": "qh",
    "MGK": "MGK",
    "Guard13007": "Guard13007",
    "Ghost_sys": "Ghost_sys",
    "G.A.I.A": "G.A.I.A",
    "PC": "PC",
    "CPU": "CPU",
    "GPU": "GPU",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "Scientific": "科学计数法",
    "Standard": "标准",
    "Blind": "盲文",
    "Letters": "字母",
    "Mixed Engineering": "混合工程",
    "Mixed Scientific": "混合科学",
    "Chemistry": "化学",
    "Engineering": "工程符号",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    'i': 'i',
    'I': 'I',
    'II': 'I',
    'III': 'III',
    'IV': 'IV',
    'V': 'V',
    'VI': 'VI',
    'VII': 'VII',
    'VIII': 'VIII',
    'X': 'X',
    'XI': 'XI',
    'XII': 'XII',
    'XIII': 'XIII',
    'XIV': 'XIV',
    'XV': 'XV',
    'XVI': 'XVI',
    'A': 'A',
    'B': 'B',
    'C': 'C',
    'D': 'D',
    'E': 'E',
    'F': 'F',
    'G': 'G',
    'H': 'H',
    'I': 'I',
    'J': 'J',
    'K': 'K',
    'L': 'L',
    'M': 'M',
    'N': 'N',
    'O': 'O',
    'P': 'P',
    'Q': 'Q',
    'R': 'R',
    'S': 'S',
    'T': 'T',
    'U': 'U',
    'V': 'V',
    'W': 'W',
    'X': 'X',
    'Y': 'Y',
    'Z': 'Z',
    '<': '<',
    '<<': '<<',
    '>': '>',
    '>>': '>>',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀，此处可以截取语句开头部分的内容进行汉化
//例如：Coin: 13、Coin: 14、Coin: 15... 这种有相同开头的语句
//可以在这里汉化开头："Coin: ":"金币: "
var cnPrefix = {
    "\n": "\n",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": " ",
    " ": " ",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "Notation: ": "符号: ",
    "Toggle Music: ": "切换声音: ",
    "VERSION: BETA ": "版本: 测试 ",
    "Release Date: ": "发布日期: ",
    "Total: ": "总计: ",
    "Reward: ": "奖励: ",
    "System CPU: ": "系统CPU: ",
    "Game by: ": "作者: ",
    "Selected File: ": "选择的文件: ",
    "Background processes": "后台进程",
    "HQ services": "HQ 服务",
    "Apps": "应用程序",
    "Hardwares: ": "硬件: ",
    "Formats: ": "格式: ",
    "Max: ": "最大: ",
    "CPS: ": "CPS: ",
    "CPS bonus: ": "CPS 奖励: ",
    "CPC: ": "CPC: ",
    "Next: ": "下一个: ",
    "MPM: ": "MPM: ",
    "Idle: ": "空闲: ",
    "Heat (": "热量 (",
    "RAM (": "内存 (",
    "Total time played: ": "游戏总时长: ",
    "Addition Task completed: ": "加法任务已完成: ",
    "Assigned: ": "已分配: ",
    "Con: ": "缺点: ",
    "contribution points: ": "贡献点: ",
    "Credit generated from Addition task: ": "加法任务产生的积分: ",
    "Credit Generated from Clicker: ": "点击器产生的积分: ",
    "Credit generated from Pressing task: ": "按下任务产生的积分: ",
    "Credit generated from Sequence task: ": "顺序任务产生的积分: ",
    "Crown coin found: ": "发现皇冠硬币: ",
    "Data gained from Addition task: ": "加法任务获得的数据: ",
    "Data gained from Pressing task: ": "压制任务获得的数据: ",
    "Data gained from Sequence task: ": "从顺序任务获得的数据: ",
    "G.A.I.A. blocked Hacks attempts: ": "G.A.I.A. 阻止黑客尝试: ",
    "G.A.I.A. blocker blocked Hacks attempts: ": "G.A.I.A. 拦截器拦截了黑客尝试: ",
    "G.A.I.A. crack password blocked Hacks attempts: ": "G.A.I.A. 破解密码被阻止 黑客尝试: ",
    "G.A.I.A. diffculity: ": "G.A.I.A. 难度: ",
    "G.A.I.A. easy blocked Hacks attempts: ": "G.A.I.A. 容易被阻止的黑客尝试: ",
    "G.A.I.A. fake certificate blocked Hacks attempts: ": "G.A.I.A. 假证书被阻止 黑客尝试: ",
    "G.A.I.A. Hacks attempts: ": "G.A.I.A. 黑客尝试: ",
    "G.A.I.A. hard blocked Hacks attempts: ": "G.A.I.A. 硬阻止黑客尝试: ",
    "G.A.I.A. impossible blocked Hacks attempts: ": "G.A.I.A. 不可能被阻止的黑客尝试: ",
    "G.A.I.A. normal blocked Hacks attempts: ": "G.A.I.A. 正常阻止的黑客尝试: ",
    "G.A.I.A. successful Hacks attempts: ": "G.A.I.A. 成功的黑客尝试: ",
    "Pressing Task completed: ": "压制任务已完成: ",
    "Sequence Task completed: ": "已完成的顺序任务: ",
    "Session Credit generated: ": "生成的会话积分: ",
    "Session Data decoded: ": "会话数据解码: ",
    "Session Materials produced: ": "制作的会议材料: ",
    "Session time played: ": "游戏会话时间: ",
    "Softwares: ": "软件: ",
    "System cooling": "系统冷却",
    "Total Clicks: ": "总点击次数: ",
    "Total Credit generated: ": "产生的总积分: ",
    "Total Credit spent: ": "花费的总积分: ",
    "Total Data Credit generated: ": "生成的总数据积分: ",
    "Total Data decoded: ": "解码总数据: ",
    "Total HQ store purchases: ": "总部商店总购买量: ",
    "Total Materials produced: ": "生产的材料总数: ",
    "Total Online store purchases: ": "在线商店购买总数: ",
    "Total Tasks completed: ": "已完成任务总数: ",
    "Total Tasks Credit generated: ": "生成的总任务积分: ",
    "Total permanent CPS multipliers: ": "总永久 CPS 乘数: ",
    "Cal ": "计算 ",
    "Contains: ": "包含: ",
    "DPS: ": "DPS: ",
    "Increase effect by ": "提高效果 ",
    "Increase Total DPS by ": "提高 总DPS ",
    "CPS bonus ": "CPS 奖励 ",
    "Download speed: ": "下载种子: ",
    "RAM usage": "内存使用率",
    "GPU usage": "GPU使用率",
    "Energy: ": "能量: ",
    "CPU usage: ": "CPU使用率: ",
    "Data decoding speed: ": "数据解码速度: ",
    "Data decoding: ": "数据解码: ",
    "Credit generating speed: ": "积分生成速度: ",
    "Credit generating: ": "积分产生: ",
    "G.A.I.A difficulity: ": "G.A.I.A难度: ",
    "Total Connection speed Multipliers: ": "总连接速度乘数: ",
    "Total Decoding Multipliers: ": "总解码乘数: ",
    "Total Energy Multipliers: ": "总能量乘数: ",
    "Total Generating Multipliers: ": "总发电乘数: ",
    "Total Production Multipliers: ": "总产量乘数: ",
    "System Cooling: ": "系统冷却: ",
    "System Energy reach: ": "系统能量达到: ",
    "System GPU: ": "系统GPU: ",
    "System heat: ": "系统热量: ",
    "System RAM: ": "系统内存: ",
    "Threat Level: ": "威胁等级: ",
    "Firewall: ": "防火墙: ",
    "Free energy: ": "免费能量: ",
    "Materials production: ": "材料制作: ",
    "Network Connection: ": "网络连接: ",
    "Watch AD to Get x": "看广告以获得 x",
    "Online decoding cores: ": "在线解码核心：",
    "Softwares CPU usage: ": "软件CPU使用率：",
    "Total CPU power usage: ": "CPU 总功耗：",
    "Total System CPU power: ": "系统 CPU 总功率：",
    "Increase Total CPS by ": "总 CPS 增加",
    "Hardwares CPU usage: ": "硬件CPU使用率：",
    "CPU power from Online store: ": "在线商店的 CPU 功率：",
    "Cores base decoding speed: ": "核心解码速度：",
    "Available CPU power: ": "可用CPU功率：",
    "CPU power from HQ: ": "HQ的 CPU 功率：",
    "Decoding speed: ": "解码速度：",
    "Keyboard v": "键盘 v",
    "Firewall v": "防火墙 v",
    "Mouse v": "鼠标 v",
    "Advanced Decoding algorithms v": "先进的解码算法 v",
    "Multithreding v": "多线程 v",
    "Click v": "点击 v",
    "Auto pressing effect ": "自动按下效果 ",
    "Auto pressing energy ": "自动按下能量 ",
    "Auto clicker effect ": "自动点击器效果 ",
    "Auto clicker energy ": "自动点击器能量 ",
    "Network listener energy ": "网络监听能量 ",
    "Network listener effect ": "网络监听效果 ",
    "Auto sequencer effect ": "自动顺序效果 ",
    "Auto addition energy ": "自动加法能量 ",
    "Exploring effect ": "探索效果 ",
    "Recycling effect ": "回收效果 ",
    "Scrapping effect ": "废料效果 ",
    "Auto addition effect ": "自动加法效果 ",
    "Auto addition sequencer ": "自动顺序能量 ",
    "Recycling production ": "回收产量 ",
    "Exploring production ": "探索产量 ",
    "Mining production ": "采矿产量 ",
    "Casting production ": "铸造产量 ",
    "Recycling energy ": "回收能量 ",
    "Exploring energy ": "探索能量 ",
    "Mining energy ": "采矿能量 ",
    "Scrapping energy ": "废料能量 ",
    "Casting energy ": "铸造能量 ",
    "Mouse conversion ": "鼠标转换 ",
    "Monitor conversion ": "监视器转换 ",
    "Solar power conversion ": "太阳能转换 ",
    "Satellite conversion ": "卫星转换 ",
    "PC conversion ": "PC电脑转换 ",
    "Desk conversion ": "桌子转换 ",
    "Radar dish conversion ": "雷达天线转换 ",
    "Radio tower conversion ": "无线电塔转换 ",
    "Router conversion ": "路由器转换 ",
    "Keyboard conversion ": "键盘转换 ",
    "Chair conversion ": "椅子转换 ",
    "Magnetic generator conversion ": "磁力发电机转换 ",
    "Mouse Prestige conversion ": "鼠标声望转换 ",
    "Satellite Prestige conversion ": "卫星声望转换 ",
    "Monitor Prestige conversion ": "监视器声望转换 ",
    "Solar power Prestige conversion ": "太阳能声望转换 ",
    "PC Prestige conversion ": "PC电脑声望转换 ",
    "Router Prestige conversion ": "路由器声望转换 ",
    "Desk Prestige conversion ": "桌子声望转换 ",
    "Magnetic generator Prestige conversion ": "磁力发电机声望转换 ",
    "Radar dish Prestige conversion ": "雷达天线声望转换 ",
    "Radio tower Prestige conversion ": "无线电塔声望转换 ",
    "Keyboard Prestige conversion ": "键盘声望转换 ",
    "Chair Prestige conversion ": "椅子声望转换 ",
    "Keyboard Mode ": "键盘模式 ",
    "Mouse Mode ": "鼠标模式 ",
    "Satellite Mode ": "卫星模式 ",
    "Router Mode ": "路由器模式 ",
    "Monitor Mode ": "监视器模式 ",
    "PC Mode ": "PC电脑模式 ",
    "Magnetic generator Mode ": "磁力发电机模式 ",
    "Radar dish Mode ": "雷达天线模式 ",
    "Radio tower Mode ": "无线电塔模式 ",
    "Solar power Mode ": "太阳能模式 ",
    "Chair Mode ": "椅子模式 ",
    "Router Prestige Mode ": "路由器声望模式 ",
    "Magnetic generator Prestige Mode ": "磁力发电机声望模式 ",
    "Keyboard Prestige Mode ": "键盘声望模式 ",
    "Mouse Prestige Mode ": "鼠标声望模式 ",
    "Satellite Prestige Mode ": "卫星声望模式 ",
    "Monitor Prestige Mode ": "监视器声望模式 ",
    "Radar dish Prestige Mode ": "雷达天线声望模式 ",
    "Solar power Prestige Mode ": "太阳能声望模式 ",
    "PC Prestige Mode ": "PC电脑声望模式 ",
    "Radio tower Prestige Mode ": "无线电塔声望模式 ",
    "Chair Prestige Mode ": "椅子声望模式 ",
    "Desk Prestige Mode ": "桌子声望模式 ",
    "Effect: ": "效果: ",
    "Click mode v": "点击模式 v",
    "Offline Materials ": "离线材料 ",
    "Offline Data ": "离线数据 ",
    "Offline Credit ": "离线积分 ",
    "Online store time ": "在线商店时间 ",
    "Online store price ": "在线商店价格 ",
    "Hardware engineering ": "硬件工程 ",
    "Software engineering ": "软件工程 ",
    "Scrapping production ": "废料生产 ",
    "Bot Manager:": "机器人管理:",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀，此处可以截取语句结尾部分的内容进行汉化
//例如：13 Coin、14 Coin、15 Coin... 这种有相同结尾的语句
//可以在这里汉化结尾：" Coin":" 金币"
var cnPostfix = {
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "  ",
    " ": " ",
    "\n": "\n",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "/sec)": "/秒)",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+)h:([\d\.]+)m:([\d\.]+)s$/,
    /^([\d\.]+)m:([\d\.]+)s$/,
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^\$([\d\.]+)$/,
    /^\(([\d\.]+)\)$/,
    /^([\d\.]+)\%$/,
    /^([\d\.]+)\/([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.,]+)$/,
    /^\(([\d\.]+)\/([\d\.]+)\)$/,
    /^(.+)路由器$/,
    /^Changed(.+)$/,
    /^Improved(.+)$/,
    /^发布日期(.+)$/,
    /^Fixed(.+)$/,
    /^Removed(.+)$/,
    /^Reduced(.+)$/,
    /^BETA(.+)$/,
    /^Added(.+)$/,
    /^Patch BETA(.+)$/,
    /^Hotfix BETA(.+)$/,
    /^成本(.+)$/,
    /^\(([\d\.]+)\%\)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)K$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+)b$/,
    /^([\d\.]+)KB$/,
    /^([\d\.]+)GB$/,
    /^([\d\.]+)MB$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+) T$/,
    /^([\d\.]+) Qi$/,
    /^([\d\.]+) Qa$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^File([\d\.,]+)$/,
    /^×([\d\.,]+)$/,
    /^\$([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+) \/ ([\d\.]+)e([\d\.,]+)$/,
    /^\$([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e\+([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
    [/^Rewards: (.+) on completing current requested task$/, '奖励：完成当前请求的任务 $1'],
    [/^Generating (.+) of total CPS$/, '生成总 CPS 的 $1'],
    [/^Generate (.+) credit per second$/, '每秒产生 $1 积分'],
    [/^Generate (.+) more$/, '产生 $1 更多'],
    [/^Install (.+) Magnatic generator$/, '安装 $1 磁力发电机'],
    [/^Install (.+) Solar power$/, '安装 $1 太阳能'],
    [/^Install (.+) Router$/, '安装 $1 路由器'],
    [/^Install (.+) Radio tower$/, '安装 $1 无线电塔'],
    [/^Install (.+) Monitor$/, '安装 $1 监视器'],
    [/^Install (.+) Satellite$/, '安装 $1 卫星'],
    [/^Install (.+) PC$/, '安装 $1 PC电脑'],
    [/^Install (.+) Mouse$/, '安装 $1 鼠标'],
    [/^Install (.+) Keyboards$/, '安装 $1 键盘'],
    [/^Install (.+) Chair$/, '安装 $1 椅子'],
    [/^Install (.+) Desk$/, '安装 $1 办公桌'],
    [/^Chair generates (.+) more for each Monitor, and Monitor generates (.+) more for each Chair$/, '每个监视器提升椅子产量 $1，每个椅子提升监视器产量 $2'],
    [/^Desk generates (.+) more for each Router, and Router generates (.+) more for each Desk$/, '每个路由器提升桌子产量 $1，每个桌子提升路由器产量 $2'],
    [/^Desk generates (.+) more for each Chair$/, '每把椅子提升 $1 桌子产量'],
    [/^Chair generates (.+) more for each Mouse$/, '每把鼠标提升 $1 椅子产量'],
    [/^Extend hibernate duration up to (.+) hours$/, '将休眠时间延长至 $1 小时'],
    [/^Extend hibernate duration up to (.+) days$/, '将休眠时间延长至 $1 天'],
    [/^Extend hibernate duration up to (.+) day$/, '将休眠时间延长至 $1 天'],
    [/^clicktinuum: \+(.+)\/Mouse$/, '点击数: \+$1\/鼠标'],
    [/^Have (.+) Hardware$/, '拥有 $1 硬件'],
    [/^\> Installed (.+) Mouse$/, '\> 已安装 $1 鼠标'],
    [/^\> Changed Hardware buy mode to ×(.+) piece$/, '\> 硬件购买模式改为 ×$2 件'],
    [/^Sequence of (.+) arrows$/, '按顺序按下 $1 箭头'],
    [/^Keep the system on for total of (.+) month and (.+) weeks$/, '使系统持续运行总计 $1 月 $2 周'],
    [/^Keep the system on for total of (.+) months and (.+) weeks$/, '使系统持续运行总计 $1 月 $2 周'],
    [/^Keep the system on for total of (.+) day$/, '使系统持续运行总计 $1 天'],
    [/^Keep the system on for total of (.+) days$/, '使系统持续运行总计 $1 天'],
    [/^Keep the system on for total of (.+) hour$/, '使系统持续运行总计 $1 小时'],
    [/^Keep the system on for total of (.+) hours$/, '使系统持续运行总计 $1 小时'],
    [/^Keep the system on for total of (.+) month$/, '使系统持续运行总计 $1 月'],
    [/^Keep the system on for total of (.+) months$/, '使系统持续运行总计 $1 月'],
    [/^Keep the system on for total of (.+) weeks$/, '使系统持续运行总计 $1 周'],
    [/^Spend total of (.+) Credit$/, '总共花费 $1 积分'],
    [/^Purchase Total of (.+) items from the Online store$/, '从在线商店购买总计 $1 件商品'],
    [/^Install (.+) Radar dish$/, '安装 $1 雷达天线'],
    [/^Decode (.+) of Data per second$/, '每秒解码 $1 数据'],
    [/^Decode (.+) data in one session$/, '在一次会话中解码 $1 数据'],
    [/^Decode total of (.+) Data$/, '总计解码 $1 数据'],
    [/^Generate total of (.+) Data from tasks$/, '从任务中生成总计 $1 数据'],
    [/^Generate total of (.+) credit from tasks$/, '从任务中生成总计 $1 积分'],
    [/^Generate total of (.+) credit by clicking$/, '从点击中生成总计 $1 积分'],
    [/^Generate total of (.+) Credit$/, '生成总计 $1 积分'],
    [/^Generate (.+) Credit in one session$/, '一次会话生成 $1 积分'],
    [/^Generate (.+) Credit per second$/, '每秒生成 $1 积分'],
    [/^Complate total of (.+) Tasks$/, '完成总计 $1 任务'],
    [/^Complate total of (.+) Addition task$/, '总计完成 $1 加法任务'],
    [/^Complate total of (.+) Pressing task$/, '总计完成 $1 按下任务'],
    [/^Complate total of (.+) Sequence task$/, '总计完成 $1 顺序任务'],
    [/^Use the Clicker (.+) times$/, '使用点击器 $1 次'],
    [/^Use the Clicker program (.+) times$/, '使用点击器程序 $1 次'],
    [/^Update your Softwares (.+) times$/, '更新您的软件 $1 次'],
    [/^Min (.+), max (.+), amount for eacy requested key$/, '每个请求密钥数量最少 $1 ，最多 $2'],
    [/^Lose (.+) loop points on incorrect input$/, '输入错误会丢失 $1 循环点数'],
    [/^Contribution points: (.+) on completing one loop$/, 'Contribution points: $1 on completing one loop'],
    [/^Gain (.+) more rewareds$/, '获得的奖励 $1'],
    [/^A Reward from HQ for collecting (.+) Contribution points$/, '收集 $1 贡献值可获得 HQ 奖励'],
    [/^Press (.+): (.+). Next: (.+)$/, '按下 $1: $2. 下一个: $3'],
	[/^([\d\.]+)\/([\d\.]+) tracking$/, '$1\/$2 追踪'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^\+([\d\.]+)\% System CPU$/, '\+$1\% 系统 CPU'],
    [/^\+([\d\.]+)\% System GPU$/, '\+$1\% 系统 GPU'],
    [/^\+([\d\.]+)\% System Ram$/, '\+$1\% 系统内存'],
    [/^\+(.+) System RAM$/, '\+$1 系统内存'],
    [/^\+(.+) System Ram$/, '\+$1 系统内存'],
    [/^\+(.+)℃ system Cooling$/, '\+$1 系统冷却'],
    [/^x([\d\.]+) keyboard$/, 'x$1 键盘'],
    [/^×([\d\.]+) Magnatic generator$/, '×$1 磁力发电机'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+) Loop points$/, '$1 循环点数'],
    [/^([\d\.,]+) ROUTER$/, '$1 路由器'],
    [/^([\d\.,]+)G communication$/, '$1G 通讯'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^and ([\d\.,]+)$/, '层级 $1'],
    [/^HQ price ([\d\.,]+)$/, 'HQ 价格 $1'],
    [/^Hibernate ([\d\.,]+)$/, '休眠 $1'],
    [/^Resources ([\d\.,]+)$/, '资源 $1'],
    [/^Tier ([\d\.,]+)$/, '层级 $1'],
    [/^Day ([\d\.,]+)$/, '天数 $1'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);