/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Default Save": "默认存档",
    "Delete": "删除",
    "No": "否",
    "Saves": "存档",
    "Options": "选项",
    "Yes": "是",
    "Are you sure?": "你确定吗？",
    "Edit Name": "编辑名称",
    "Info": "信息",
    "Currently:": "当前:",
    "Appearance": "外观",
    "How the game looks.": "游戏看起来如何。",
    "Theme": "主题",
    "Show milestones": "显示里程碑",
    "Show TPS meter at the bottom-left corner of the page.": "在页面左下角显示 TPS。",
    "Show TPS": "显示 TPS",
    "None": "无",
    "Align modifier units": "对齐概览单位",
    "Align numbers to the beginning of the unit in modifier view.": "在概览视图中将数字与单元的开头对齐。",
    "Select which milestones to display based on criterias.": "根据标准选择要显示的里程碑。",
    "All": "全部",
    "Classic": "经典",
    "Configurable": "可配置",
    "Duplicate": "复制",
    "Mute": "静音",
    "Unmute": "播放",
    "New Game": "新游戏",
    "Normal": "普通",
    "Name": "名称",
    "OK": "确定",
    "Network": "网络",
    "Network connec": "网络连接",
    "Max": "最大",
    "Last Played": "最近游戏",
    "Keyboard": "键盘",
    "Automation bots": "自动化机器人",
    "Click": "点击",
    "Click mode": "点击模式",
    "Booting...": "正在启动...",
    "Confirm": "确认",
    "Confirm selection": "确认选项",
    "Console": "控制台",
    "Console Idle": "控制台放置",
    "Continue": "继续",
    "Welcome": "欢迎",
    "Toggle Auto block": "切换自动阻止",
    "Updates Notes": "更新日志",
    "Toggle Auto Software Install": "切换自动软件安装",
    "Updates": "更新",
    "Hrdwares": "硬件",
    "Idle repoert": "放置报表",
    "Idle report": "放置报告",
    "Install All": "全部安装",
    "Listener": "监听器",
    "Logout": "登出",
    "Lord Beranda": "勋爵之家",
    "Format": "格式",
    "Fixes:": "修复:",
    "Easy": "简单",
    "Details": "详情",
    "Data": "数据",
    "Creation Date": "创建日期",
    "Computing": "计算",
    "Export save file": "导出存档文件",
    "Exported save file": "已导出存档",
    "Exploring": "探索中",
    "Firewall": "防火墙",
    "Pause": "暂停",
    "Hard": "困难",
    "Green": "绿色",
    "Return": "返回",
    "Resume": "返回",
    "RESET": "重置",
    "Reset": "重置",
    "Reset Tutorials": "重置教程",
    "Save file": "存档文件",
    "Save File": "存档文件",
    "Dowloands": "下载",
    "Downloading, Please wait...": "正在下载，请稍候...",
    "Store": "商店",
    "Filtering": "筛选",
    "General": "常规",
    "GET": "获取",
    "Generator": "发电机",
    "HACKED": "黑客入侵",
    "Hardwares": "硬件",
    "Heat": "热量",
    "Hibernate": "休眠",
    "HQ store": "HQ 商店",
    "Importing...": "导入...",
    "Software": "软件",
    "Softwares": "软件",
    "Solar power": "太阳能",
    "Sorting": "排序",
    "System": "系统",
    "System Color": "系统颜色",
    "System Manager": "系统管理员",
    "Tasks": "任务",
    "Task progress menu is now resizable": "任务进度菜单现在可调整大小",
    "Tasks now can be pasued/Resumed": "现在可以暂停/恢复任务",
    "The Authors of the icons are:": "图标的作者是：",
    "Turn OFF": "关掉",
    "TURN OFF": "关掉",
    "TURN ON": "打开",
    "Turn ON": "打开",
    "Turn OFF/ON idle report": "关闭/打开 放置报告",
    "Warehouse": "仓库",
    "Mouse": "鼠标",
    "Network, Please wait...": "网络，请稍等...",
    "OR Gate": "或门",
    "NOT Gate": "非门",
    "NAND Gate": "与非门",
    "NOR Gate": "或非门",
    "XOR Gate": "异或门",
    "Note: If Game still freezing or CPS not working, please send a feedback": "注意：如果游戏仍然冻结或 CPS 无法工作，请发送反馈",
    "Online Store": "在线商店",
    "Online store now will not show you upgrades for Hardwares that are not unlocked yet": "在线商店现在不会向您显示尚未解锁的硬件的升级",
    "Performance": "性能",
    "Retrigger all Tutorials": "重新触发所有教程",
    "Router": "路由器",
    "Satellite": "卫星",
    "'Cancel' Button in Format menu is now always visible": "“格式”菜单中的“取消”按钮现在始终可见",
    "%/Task": "%/任务",
    "> Changed to 'Pressing' Task on Easy mode": "> 更改为简易模式下的“按下”任务",
    "> Registration complate, Welcome Agent.": "> 登记已完成，欢迎新代理。",
    "> Save complete.": "> 保存完成。",
    "> saving...": "> 正在保存...",
    "Pressing": "按下",
    "Radio tower": "无线电塔",
    "Radar dish": "雷达天线",
    "Recycling": "回收",
    "Withdraw": "提取",
    "Systems": "系统",
    "Skoll": "斯科尔",
    "Sequence": "序列",
    "Sequencer": "序列器",
    "Select a File": "选择一个文件",
    "Scrapping": "报废",
    "Red": "红色",
    "RAM": "内存",
    "sbed": "错误检测",
    "Probably Fixed a bug where saving sometimes fail, Note: Refreshing the page might cause lose of all progress from last auto save, this is caused by browsers design, nothing i can do here, so please make sure to manually save before refreshing the page.": "可能修复了有时保存失败的错误，注意：刷新页面可能会导致上次自动保存的所有进度丢失，这是由浏览器设计引起的，我在这里无能为力，所以请确保在刷新页面之前手动保存。",
    "Lorc": "洛克希德公司无线电指令",
    ", under the terms of the Creative": "，根据创意条款",
    "A random sabotage effect will be applied, eicher Reducing CPS, DPS, CPC, MPM, Energy, or Network": "将应用随机破坏效果，即减少 CPS、DPS、CPC、MPM、能量或网络",
    "Achievement": "成就",
    "Add": "添加",
    "Adder": "加法器",
    "Adjusted all 'Advanced Decoding algorithms' softwares prices": "调整了所有“高级解码算法”软件的价格",
    "Adjusted All three tasks": "调整了全部三项任务",
    "Adjusted G.A.I.A Hack attempts intervelas, HACKS are less frequent in general": "调整后的 G.A.I.A 黑客尝试间隔，总体而言黑客攻击频率较低",
    "Adjusted in Tasks menu 'Overflow', 'Infinite keys' information text, to be more detailed.": "调整了任务菜单“溢出”、“无限键”信息文本，更加详细。",
    "All menus now should remember their status, position, size, opened or not, expanded or not": "现在所有菜单都应该记住它们的状态、位置、大小、是否打开、是否展开",
    "All menus will auto reset if 'Auto reset' is ON": "如果“自动重置”打开，所有菜单将自动重置",
    "All new precedures from Bot manager will also be calculated in Idle if they are active but not in Hibernate": "如果 Bot 管理器中的所有新程序处于活动状态，但不在 Hibernate 中，则它们也将在 Idle 中计算",
    "All Original icons assets are from": "所有原始图标资源均来自",
    "All three Tasks now have the same software effects, it is up to your preference to choose to invest and upgrade:": "现在三个任务的软件效果是一样的，可以根据自己的喜好选择投资升级：",
    "Analysis": "分析",
    "AND Gate": "与门",
    "Are you sure to PERMENENTLY reset current save file?": "您确定要永久重置当前保存文件吗？",
    "Assemble": "集合",
    "Assign": "分配",
    "Auto": "汽车",
    "Balancing:": "平衡：",
    "Battle bots": "战斗机器人",
    "Blue": "蓝色的",
    "Bot Manager": "机器人经理",
    "Cancel": "取消",
    "Casting": "铸件",
    "Chair": "椅子",
    "Change Listener bot effect to directly increase DPS": "改变Listener bot效果直接增加DPS",
    "Changes": "变化",
    "Changes:": "变化：",
    "Click on Effect viewer to toggle between pinning effect list or not, this helps when you want to scroll the list": "单击效果查看器可在是否固定效果列表之间切换，这在您想要滚动列表时很有帮助",
    "Clicker": "唱首歌",
    "Commons 3.0 BY license": "Commons 3.0 BY 许可证",
    "Completely new UI": "全新的用户界面",
    "Contact": "接触",
    "CPS and DPS AD Multipliers can now be increased up to x8 and increase duration to 20mins": "CPS 和 DPS AD 乘数现在可增加至 x8，并将持续时间增加至 20 分钟",
    "Credit": "信用",
    "Credits": "制作人员",
    "Currencies": "货币",
    "Decoder_agent": "解码器代理",
    "Decreased all Advanced Decoding algorithms software prices and condition to unlock": "降低了所有高级解码算法软件的价格和解锁条件",
    "defence bots": "防御机器人",
    "Delapouite": "德拉普伊特",
    "Desk": "桌子",
    "Details page in System manager is now divided into sections for easier reading": "系统管理器中的详细信息页面现在分为多个部分，以便于阅读",
    "Energy": "活力",
    "Enter": "进入",
    "Extended basic tutorial to include an explanation about CPU, GPU, RAM, and Heat mechanics": "扩展基础教程，包括有关 CPU、GPU、RAM 和热机制的说明",
    "Extended main Tutorial pop-up messages to include an explanation about the Effect viewer": "扩展了主要教程弹出消息，包括有关效果查看器的说明",
    "FAN": "扇子",
    "G.A.I.A ADS Network_spy": "G.A.I.A ADS Network_spy",
    "G.A.I.A will sabotage the System for X minutes and X effect power, depending on Hack difficulty and G.A.I.A difficulty": "G.A.I.A 将破坏系统 X 分钟和 X 效果强度，具体取决于 Hack 难度和 G.A.I.A 难度",
    "game-icons.net": "游戏图标.net",
    "General performance improvements": "一般性能改进",
    "General Performance improvements": "一般性能改进",
    "General Software and hardware prices balancing": "一般软件和硬件价格平衡",
    "General visual improvements, and typo fixes": "一般视觉改进和拼写错误修复",
    "General Visual improvements, and typo fixes": "一般视觉改进和拼写错误修复",
    "General Visual improvments": "一般视觉改善",
    "General visual improvments, and typo fixes": "一般视觉改进和拼写错误修复",
    "General Visual polishing": "一般视觉抛光",
    "Green, Red, and Blue System's themes have been adjusted to fit the new UI": "绿色、红色和蓝色系统的主题已调整以适应新的用户界面",
    "Hardware resources consumption info now will change depending on current selected buy mode": "硬件资源消耗信息现在将根据当前选择的购买模式而变化",
    "Hardware's generating rate text info now includes the CPS ad multiplier.": "硬件的生成率文本信息现在包括 CPS 广告乘数。",
    "Hitting Walls or Seekers will end the HACK instantly resulting in being Hacked": "撞墙或搜索者将立即结束 HACK，导致被黑客攻击",
    "Idle generating is now affected by AD x2 CPS, DPS, for the buff duration": "空闲生成现在在 buff 持续时间内受到 AD x2 CPS、DPS 的影响",
    "improved main icons visuals, it is now almost similar to windows icons behavior": "改进了主图标的视觉效果，现在几乎与 Windows 图标行为相似",
    "Increased \"Tasks\" Tier 5 reward": "增加“任务”5级奖励",
    "Increased all Auto clicker effect node in format tree from +2% -> +3%": "增加格式树中所有自动点击器效果节点从 +2% -> +3%",
    "Increased all conditions of generated Credit from Addition Tasks": "增加了从附加任务中生成信用的所有条件",
    "Increased all conditions of total Hardwares and softwares achievements": "增加了总硬件和软件成就的所有条件",
    "Increased all Credits generated from tasks achievements conditions": "增加了任务成就条件产生的所有积分",
    "Increased all DPS achievements conditions": "增加了所有 DPS 成就条件",
    "Increased All Format nodes prices": "提高了所有格式节点的价格",
    "Increased almost all Online items effect by at least x3 depending on the item": "将几乎所有在线物品的效果增加至少 x3，具体取决于物品",
    "Increased Basic: CPS, DPS, CLICK": "增加基础：CPS、DPS、CLICK",
    "Increased Computing, Frequency, and all Gates softwares effects, now they give more CPS bonuses, and their descriptions is more clear": "增加了计算、频率和所有盖茨软件的效果，现在它们提供更多的CPS奖励，并且它们的描述更清晰",
    "Increased Credit and Data gain when successfully blocking a HACK, blocking Impossible difficulty is now significantly more rewarding": "成功阻止黑客攻击时，信用和数据增益增加，阻止不可能的难度现在明显更有价值",
    "Increased Credit gain when blocking HACK!": "阻止黑客攻击时增加信用增益！",
    "Increased Credit loss when HACKED!": "被黑客攻击时信用损失增加！",
    "Increased Crown Coin effect:": "增加皇冠币效果：",
    "Increased Data analysis and filtering program effect, now they give more DPS bonuses, and their description is more clear": "增加了数据分析和过滤程序效果，现在它们给予更多的DPS加成，并且它们的描述更清晰",
    "Increased Data gain when blocking HACK!": "阻止 HACK 时增加数据增益！",
    "Increased Data loss when HACKED!": "黑客攻击时数据丢失增加！",
    "increased Date requirement in Format tree for Firewall, Resourecs, Advanced decoding algorithem, Multithriding, and Store nodes tree": "增加了防火墙、资源、高级解码算法、多重处理和存储节点树的格式树中的日期要求",
    "Increased Firewall effect from increasing 2.5% per level to 5% per level": "防火墙效果从每级 2.5% 增加到每级 5%",
    "Increased Network listener effect node in format tree from +0.1% -> +0.2%": "格式树中的网络侦听器效果节点从 +0.1% -> +0.2% 增加",
    "Increased Online item sizes": "增加在线物品尺寸",
    "Increased Pressing task software unlocking conditions": "增加压制任务软件解锁条件",
    "Increased Pressing Tsk complation points from 20 to 25": "Pressing Tsk 编译点从 20 增加到 25",
    "Increased Rare: DPS": "增加稀有：DPS",
    "Increased Uncommon: DPS, CLICK": "增加罕见：DPS、点击",
    "Install all currently affordable Softwares": "安装所有当前负担得起的软件",
    "Installed Sequence softwares will be now showing in Software Page in System manager": "已安装的序列软件现在将显示在系统管理器的软件页面中",
    "MangOperations": "芒运营",
    "Material production": "材料生产",
    "Materials": "材料",
    "Mining": "采矿",
    "Miscellaneous": "杂项",
    "Monitor": "监视器",
    "New objective: reach the goal in the Lower right corner before times up": "新目标：在时间结束前到达右下角的目标",
    "New System lock visuals when Threat reaches 100%+": "当威胁达到 100% 以上时，新的系统锁定视觉效果",
    "New Tasks system:": "新任务系统：",
    "No effect currently activated": "当前未激活任何效果",
    "Now all Tasks can be played on Three difficulties, Easy, Normal, and Hard": "现在所有任务都可以在三种难度下进行：简单、普通和困难",
    "Now G.A.I.A will get bit by bit stronger with each Format, Hacks will be more frequent, difficult Hacks will appear more, and greater sabotaging when successfully hacked": "现在G.A.I.A的每种格式都会变得越来越强大，黑客攻击将会更加频繁，困难的黑客攻击将会出现更多，成功黑客攻击后破坏性也会更大",
    "NXOR Gate": "异或门",
    "Onion_protiection": "洋葱保护",
    "Open Updates patch notes": "打开更新补丁说明",
    "Permanently delete current save file": "永久删除当前保存文件",
    "Permanently reset currenct save file": "永久重置当前保存文件",
    "Presser": "压机",
    "Pressing, Addition, and Sequence Credit multipliers are changed to increase base Credit gain instead of increasing generally": "按下、加法和顺序信用乘数已更改，以增加基本信用增益，而不是普遍增加",
    "Pressing, Addition, and Sequence rewards multiplers are changed to scale with current CPS and DPS for each keyboard instead of increasing by fixed number, this way tasks rewards will always be meaningful and engaging!": "按下、加法和顺序奖励倍数会根据每个键盘的当前 CPS 和 DPS 进行调整，而不是按固定数字增加，这样任务奖励将始终有意义且有吸引力！",
    "Problebly fixed a bug where icons images sometimes does not load": "可能修复了图标图像有时无法加载的错误",
    "Procedure": "程序",
    "Processes": "流程",
    "Production": "生产",
    "Researched Format nods will now glow in gold": "研究的格式点头现在将发出金色光芒",
    "Second attempt to fix saving issues. Please provide feedback if bugs persist": "第二次尝试解决保存问题。 如果错误仍然存在，请提供反馈",
    "See Balancing section for more information": "有关详细信息，请参阅平衡部分",
    "Select a File": "选择一个文件",
    "Selected File: File09012024134339": "选定的文件：File09012024134339",
    "Slightly increased Credit gain when Blocking a HACK": "阻止黑客攻击时的信用增益略有增加",
    "Slightly increased Credit loss when Hacked": "被黑客攻击时信用损失略有增加",
    "Slightly increased HQ items prices": "总部物品价格小幅上涨",
    "Slightly increased Keyboard and Mouse bonus effect from online store": "略微增加了在线商店的键盘和鼠标奖励效果",
    "Slightly increased Online items prices": "线上商品价格小幅上涨",
    "Slightly increased Online items sizes": "略微增加在线商品尺寸",
    "Software page in expanded System Manager now shows the current software's effect": "扩展系统管理器中的软件页面现在显示当前软件的效果",
    "Some visual have been removed and some have been repositioned": "一些视觉效果已被删除，一些已重新定位",
    "The old G.A.I.A sabotage mechanic proved to be more frustrating than creating a challenge, and it comes with design flaws, so here's the new sabotage mechanic: When Hacked by G.A.I.A": "事实证明，旧的 G.A.I.A 破坏机制比创造挑战更令人沮丧，而且它存在设计缺陷，所以这是新的破坏机制：当被 G.A.I.A 黑客攻击时",
    "Updated all pop-up tutorials texts to fit the new style": "更新了所有弹出教程文本以适应新风格",
    "With the introduction of the new effects system, fixed Crown coins animation and effects gets buggy if Crown coin taken by normal method then from Gift AD sequanthally": "随着新效果系统的引入，修复了如果通过正常方法获取皇冠币然后从礼物 AD 中获取皇冠币的话，固定的皇冠币动画和效果会出现问题",
    "With the introduction of the new UI, all old bugs related to menus such as unable to resize, reposition, or contents out of boundaries, all are now irrelevant to this new UI": "随着新 UI 的引入，所有与菜单相关的旧错误（例如无法调整大小、重新定位或内容超出边界）现在都与此新 UI 无关",
    "With the introduction of the new UI, scroll bars can now be added without breaking anything": "随着新 UI 的引入，现在可以添加滚动条而不会破坏任何内容",
    "You can now double click save file to start the game": "您现在可以双击保存文件来开始游戏",
    "You can now expand System manager menu to get detailed information about the system": "您现在可以展开系统管理器菜单来获取有关系统的详细信息",
    "> Welcome back Agent.": "> 欢迎回来代理。",
    "Press L: 16. Next: K": "按 L：16。下一个：K",
    "> Changed to 'Addition' Task on Easy mode": "> 更改为简单模式下的“加法”任务",
    "> Changed to 'Sequence' Task on Easy mode": "> 更改为简单模式下的“顺序”任务",
    "A Task given by HQ": "总部交给的任务",
    "Addition": "添加",
    "Contribution progression": "贡献进展",
    "Correctly enter given arrow sequence using keyboard arrows keys": "使用键盘箭头键正确输入给定的箭头序列",
    "Get Rewards from HQ when collecting 10, 25, 40, 55, and 100 Contribution points": "累积10、25、40、55、100点贡献值即可获得总部奖励",
    "In HQ store, you can buy CPU, GPU, RAM, or FAN, these items will help you extend System's resources power, be careful as they all share same price, so only buy what is needed the most": "在总部商店，你可以购买CPU、GPU、RAM或FAN，这些物品将帮助你扩展系统的资源能力，要小心，因为它们的价格相同，所以只买最需要的东西",
    "Item Price: ": "商品价格：",
    "Pasue/Resume": "暂停/恢复",
    "Pause/Resume button, to receive inputs towards tasks or not": "暂停/恢复按钮，用于接收或不接收任务输入",
    "Repeatedly press requested keyboard key x amount of times": "重复按请求的键盘按键 x 次",
    "Shows current Contribution points progression for the next HQ Contribution reward": "显示下一个总部贡献奖励的当前贡献点数进度",
    "Solve given Addition problems and find the value of (?) where its presented": "解决给定的加法问题并找到 (?) 出现的值",
    "Unable to connect to \"Online Store": "无法连接到“在线商店”",
    "When paused, inputs will not be counted towards tasks progression": "暂停时，输入将不计入任务进度",
    "you need at least 1 Router installed": "您至少需要安装 1 个路由器",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "Guard13007": "Guard13007",
    "Ghost_sys": "Ghost_sys",
    "G.A.I.A": "G.A.I.A",
    "PC": "PC",
    "CPU": "CPU",
    "GPU": "GPU",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "Scientific": "科学计数法",
    "Standard": "标准",
    "Blind": "盲文",
    "Letters": "字母",
    "Mixed Engineering": "混合工程",
    "Mixed Scientific": "混合科学",
    "Chemistry": "化学",
    "Engineering": "工程符号",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    'i': 'i',
    'I': 'I',
    'II': 'I',
    'III': 'III',
    'IV': 'IV',
    'V': 'V',
    'VI': 'VI',
    'VII': 'VII',
    'VIII': 'VIII',
    'X': 'X',
    'XI': 'XI',
    'XII': 'XII',
    'XIII': 'XIII',
    'XIV': 'XIV',
    'XV': 'XV',
    'XVI': 'XVI',
    'A': 'A',
    'B': 'B',
    'C': 'C',
    'D': 'D',
    'E': 'E',
    'F': 'F',
    'G': 'G',
    'H': 'H',
    'I': 'I',
    'J': 'J',
    'K': 'K',
    'L': 'L',
    'M': 'M',
    'N': 'N',
    'O': 'O',
    'P': 'P',
    'Q': 'Q',
    'R': 'R',
    'S': 'S',
    'T': 'T',
    'U': 'U',
    'V': 'V',
    'W': 'W',
    'X': 'X',
    'Y': 'Y',
    'Z': 'Z',
    '<': '<',
    '<<': '<<',
    '>': '>',
    '>>': '>>',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀，此处可以截取语句开头部分的内容进行汉化
//例如：Coin: 13、Coin: 14、Coin: 15... 这种有相同开头的语句
//可以在这里汉化开头："Coin: ":"金币: "
var cnPrefix = {
    "\n": "\n",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": " ",
    " ": " ",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "Notation: ": "符号: ",
    "Toggle Music: ": "切换声音: ",
    "VERSION: BETA ": "版本: 测试 ",
    "Release Date: ": "发布日期: ",
    "Total: ": "总计: ",
    "Reward: ": "奖励: ",
    "System CPU: ": "系统CPU: ",
    "Game by: ": "作者: ",
    "Selected File: ": "选择的文件: ",
    "Background processes": "后台进程",
    "HQ services": "HQ 服务",
    "Apps": "应用程序",
    "Hardwares: ": "硬件: ",
    "Formats: ": "格式: ",
    "Max: ": "最大: ",
    "CPS: ": "CPS: ",
    "CPS bonus: ": "CPS 奖励: ",
    "CPC: ": "CPC: ",
    "Next: ": "下一个: ",
    "MPM: ": "MPM: ",
    "Idle: ": "空闲: ",
    "Heat (": "热量 (",
    "RAM (": "内存 (",
    "Total time played: ": "游戏总时长: ",
    "Addition Task completed: ": "添加任务已完成: ",
    "Assigned: ": "已分配: ",
    "Con: ": "缺点: ",
    "contribution points: ": "贡献点: ",
    "Credit generated from Addition task: ": "添加任务产生的积分: ",
    "Credit Generated from Clicker: ": "点击器产生的积分: ",
    "Credit generated from Pressing task: ": "按下任务产生的积分: ",
    "Credit generated from Sequence task: ": "序列任务产生的积分: ",
    "Crown coin found: ": "发现皇冠硬币: ",
    "Data gained from Addition task: ": "加法任务获得的数据: ",
    "Data gained from Pressing task: ": "压制任务获得的数据: ",
    "Data gained from Sequence task: ": "从序列任务获得的数据: ",
    "G.A.I.A. blocked Hacks attempts: ": "G.A.I.A. 阻止黑客尝试: ",
    "G.A.I.A. blocker blocked Hacks attempts: ": "G.A.I.A. 拦截器拦截了黑客尝试: ",
    "G.A.I.A. crack password blocked Hacks attempts: ": "G.A.I.A. 破解密码被阻止 黑客尝试: ",
    "G.A.I.A. diffculity: ": "G.A.I.A. 难度: ",
    "G.A.I.A. easy blocked Hacks attempts: ": "G.A.I.A. 容易被阻止的黑客尝试: ",
    "G.A.I.A. fake certificate blocked Hacks attempts: ": "G.A.I.A. 假证书被阻止 黑客尝试: ",
    "G.A.I.A. Hacks attempts: ": "G.A.I.A. 黑客尝试: ",
    "G.A.I.A. hard blocked Hacks attempts: ": "G.A.I.A. 硬阻止黑客尝试: ",
    "G.A.I.A. impossible blocked Hacks attempts: ": "G.A.I.A. 不可能被阻止的黑客尝试: ",
    "G.A.I.A. normal blocked Hacks attempts: ": "G.A.I.A. 正常阻止的黑客尝试: ",
    "G.A.I.A. successful Hacks attempts: ": "G.A.I.A. 成功的黑客尝试: ",
    "Pressing Task completed: ": "压制任务已完成: ",
    "Sequence Task completed: ": "已完成的序列任务: ",
    "Session Credit generated: ": "生成的会话积分: ",
    "Session Data decoded: ": "会话数据解码: ",
    "Session Materials produced: ": "制作的会议材料: ",
    "Session time played: ": "游戏会话时间: ",
    "Softwares: ": "软件: ",
    "System cooling": "系统冷却",
    "Total Clicks: ": "总点击次数: ",
    "Total Credit generated: ": "产生的总积分: ",
    "Total Credit spent: ": "花费的总积分: ",
    "Total Data Credit generated: ": "生成的总数据信用: ",
    "Total Data decoded: ": "解码总数据: ",
    "Total HQ store purchases: ": "总部商店总购买量: ",
    "Total Materials produced: ": "生产的材料总数: ",
    "Total Online store purchases: ": "在线商店购买总数: ",
    "Total Tasks completed: ": "已完成任务总数: ",
    "Total Tasks Credit generated: ": "生成的总任务积分: ",
    "Total permanent CPS multipliers: ": "总永久 CPS 乘数: ",
    "Cal ": "计算 ",
    "Contains: ": "包含: ",
    "DPS: ": "DPS: ",
    "Increase effect by ": "提高效果 ",
    "Increase Total DPS by ": "提高 总DPS ",
    "CPS bonus ": "CPS 奖励 ",
    "Download speed: ": "下载种子: ",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀，此处可以截取语句结尾部分的内容进行汉化
//例如：13 Coin、14 Coin、15 Coin... 这种有相同结尾的语句
//可以在这里汉化结尾：" Coin":" 金币"
var cnPostfix = {
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "  ",
    " ": " ",
    "\n": "\n",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "/sec)": "/秒)",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+)h:([\d\.]+)m:([\d\.]+)s$/,
    /^([\d\.]+)m:([\d\.]+)s$/,
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^\$([\d\.]+)$/,
    /^\(([\d\.]+)\)$/,
    /^([\d\.]+)\%$/,
    /^([\d\.]+)\/([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.,]+)$/,
    /^\(([\d\.]+)\/([\d\.]+)\)$/,
    /^Changed(.+)$/,
    /^Improved(.+)$/,
    /^发布日期(.+)$/,
    /^Fixed(.+)$/,
    /^Removed(.+)$/,
    /^Reduced(.+)$/,
    /^BETA(.+)$/,
    /^Added(.+)$/,
    /^Patch BETA(.+)$/,
    /^Hotfix BETA(.+)$/,
    /^成本(.+)$/,
    /^\(([\d\.]+)\%\)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)K$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+)b$/,
    /^([\d\.]+)KB$/,
    /^([\d\.]+)MB$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+) T$/,
    /^([\d\.]+) Qi$/,
    /^([\d\.]+) Qa$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^File([\d\.,]+)$/,
    /^×([\d\.,]+)$/,
    /^\$([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+) \/ ([\d\.]+)e([\d\.,]+)$/,
    /^\$([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e\+([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
    [/^Gain (.+) more rewareds$/, '获得的奖励 $1'],
    [/^A Reward from HQ for collecting (.+) Contribution points$/, '收集 $1 贡献值可获得 HQ 奖励'],
    [/^Press (.+): (.+). Next: (.+)$/, '按下 $1: $2. 下一个: $3'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^\+([\d\.]+)\% System CPU$/, '\+$1\% 系统 CPU'],
    [/^\+([\d\.]+)\% System GPU$/, '\+$1\% 系统 GPU'],
    [/^\+([\d\.]+)\% System Ram$/, '\+$1\% 系统内存'],
    [/^\+(.+) System Ram$/, '\+$1 系统内存'],
    [/^×([\d\.]+) keyboard$/, '×$1 键盘'],
    [/^×([\d\.]+) Magnatic generator$/, '×$1 磁力发电机'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+) ROUTER$/, '$1 路由器'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^Tier ([\d\.,]+)$/, '层级 $1'],
    [/^Day ([\d\.,]+)$/, '天数 $1'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);